import { Category, Block } from './types';

export const INFLUENCER_CATEGORIES: Category[] = [
  { id: 'result', label: 'Resultado Visual', icon: 'Image', color: 'text-blue-400' },
  { id: 'focus', label: 'Enfoque Principal', icon: 'Crosshair', color: 'text-indigo-400' },
  { id: 'scene', label: 'Tipo de Escena', icon: 'MapPin', color: 'text-cyan-400' },
  { id: 'environment', label: 'Ambientación', icon: 'Cloud', color: 'text-sky-400' },
  { id: 'action', label: 'Acción / Situación', icon: 'Activity', color: 'text-teal-400' },
  { id: 'movement', label: 'Movimiento', icon: 'Wind', color: 'text-emerald-400' },
  { id: 'gesticulation', label: 'Gesticulación', icon: 'Smile', color: 'text-green-400' },
  { id: 'exposed_body', label: 'Partes Expuestas', icon: 'User', color: 'text-lime-400' },
  { id: 'camera', label: 'Cámara / Ángulo', icon: 'Camera', color: 'text-yellow-400' },
  { id: 'lens', label: 'Lentes / Parámetros', icon: 'Aperture', color: 'text-amber-400' },
  { id: 'lighting', label: 'Iluminación', icon: 'Sun', color: 'text-orange-400' },
  { id: 'realism', label: 'Realismo', icon: 'Eye', color: 'text-red-400' },
  { id: 'outfit', label: 'Outfit / Styling', icon: 'Shirt', color: 'text-rose-400' },
  { id: 'makeup', label: 'Maquillaje', icon: 'Sparkles', color: 'text-fuchsia-300' },
  { id: 'color', label: 'Paleta / Color', icon: 'Palette', color: 'text-pink-400' },
  { id: 'props', label: 'Fondo y Props', icon: 'Box', color: 'text-fuchsia-400' },
  { id: 'intention', label: 'Intención', icon: 'Target', color: 'text-purple-400' },
  { id: 'body_details', label: 'Detalles del Cuerpo', icon: 'User', color: 'text-rose-300' },
  { id: 'quality', label: 'Calidades de Imagen', icon: 'Sparkles', color: 'text-yellow-300' },
  { id: 'negative', label: 'Restricciones', icon: 'ShieldAlert', color: 'text-zinc-400' },
];

export const GENERAL_CATEGORIES: Category[] = [
  { id: 'gen_style', label: 'Estilo Artístico', icon: 'Palette', color: 'text-pink-400' },
  { id: 'gen_subject', label: 'Sujeto Principal', icon: 'Box', color: 'text-blue-400' },
  { id: 'gen_environment', label: 'Entorno / Paisaje', icon: 'Map', color: 'text-emerald-400' },
  { id: 'gen_lighting', label: 'Iluminación', icon: 'Sun', color: 'text-orange-400' },
  { id: 'gen_camera', label: 'Cámara / Composición', icon: 'Camera', color: 'text-yellow-400' },
  { id: 'gen_mood', label: 'Atmósfera / Mood', icon: 'Cloud', color: 'text-purple-400' },
  { id: 'gen_color', label: 'Paleta de Color', icon: 'Droplet', color: 'text-cyan-400' },
  { id: 'gen_quality', label: 'Calidades de Imagen', icon: 'Sparkles', color: 'text-yellow-300' },
  { id: 'gen_details', label: 'Nivel de Detalle', icon: 'Search', color: 'text-rose-400' },
];

export const GENERAL_BLOCKS: Block[] = [
  // Estilo Artístico
  { id: 'gs_1', categoryId: 'gen_style', label: 'Fotografía Realista', value: 'hyper-realistic photography, 8k resolution' },
  { id: 'gs_2', categoryId: 'gen_style', label: 'Ilustración Digital', value: 'digital illustration, vibrant colors' },
  { id: 'gs_3', categoryId: 'gen_style', label: 'Pintura al Óleo', value: 'oil painting style, visible brushstrokes' },
  { id: 'gs_4', categoryId: 'gen_style', label: 'Arte Conceptual', value: 'concept art, highly detailed' },
  { id: 'gs_5', categoryId: 'gen_style', label: 'Cyberpunk', value: 'cyberpunk aesthetic, neon lights, futuristic' },
  { id: 'gs_6', categoryId: 'gen_style', label: 'Steampunk', value: 'steampunk style, brass, gears, victorian' },
  { id: 'gs_7', categoryId: 'gen_style', label: 'Acuarela', value: 'watercolor painting, soft edges, translucent' },
  { id: 'gs_8', categoryId: 'gen_style', label: 'Anime / Manga', value: 'anime style, studio ghibli aesthetic' },
  { id: 'gs_9', categoryId: 'gen_style', label: 'Low Poly / 3D', value: 'low poly 3d render, isometric view' },

  // Sujeto Principal
  { id: 'gsu_1', categoryId: 'gen_subject', label: 'Arquitectura Moderna', value: 'modern architecture building' },
  { id: 'gsu_2', categoryId: 'gen_subject', label: 'Vehículo Futurista', value: 'futuristic flying vehicle' },
  { id: 'gsu_3', categoryId: 'gen_subject', label: 'Criatura Fantástica', value: 'mythical fantasy creature' },
  { id: 'gsu_4', categoryId: 'gen_subject', label: 'Objeto Cotidiano', value: 'everyday object, still life' },
  { id: 'gsu_5', categoryId: 'gen_subject', label: 'Comida / Bebida', value: 'delicious food photography, appetizing' },
  { id: 'gsu_6', categoryId: 'gen_subject', label: 'Ruinas Antiguas', value: 'ancient ruins, overgrown with vegetation' },
  { id: 'gsu_7', categoryId: 'gen_subject', label: 'Nave Espacial', value: 'sci-fi spaceship exterior' },

  // Entorno / Paisaje
  { id: 'ge_1', categoryId: 'gen_environment', label: 'Ciudad Futurista', value: 'futuristic metropolis cityscape' },
  { id: 'ge_2', categoryId: 'gen_environment', label: 'Bosque Mágico', value: 'enchanted magical forest, glowing plants' },
  { id: 'ge_3', categoryId: 'gen_environment', label: 'Desierto', value: 'vast desert landscape, sand dunes' },
  { id: 'ge_4', categoryId: 'gen_environment', label: 'Montañas Nevadas', value: 'snow-capped mountain peaks' },
  { id: 'ge_5', categoryId: 'gen_environment', label: 'Fondo Submarino', value: 'underwater scene, coral reef, sun rays' },
  { id: 'ge_6', categoryId: 'gen_environment', label: 'Espacio Exterior', value: 'outer space, nebula, stars, galaxies' },
  { id: 'ge_7', categoryId: 'gen_environment', label: 'Interior Acogedor', value: 'cozy indoor room, warm fireplace' },

  // Iluminación
  { id: 'gl_1', categoryId: 'gen_lighting', label: 'Luz Natural (Día)', value: 'natural daylight, bright and clear' },
  { id: 'gl_2', categoryId: 'gen_lighting', label: 'Golden Hour', value: 'golden hour lighting, warm sun rays' },
  { id: 'gl_3', categoryId: 'gen_lighting', label: 'Iluminación de Estudio', value: 'professional studio lighting, softbox' },
  { id: 'gl_4', categoryId: 'gen_lighting', label: 'Luz de Neón', value: 'neon lighting, vibrant pink and blue glows' },
  { id: 'gl_5', categoryId: 'gen_lighting', label: 'Luz de Luna', value: 'moonlight, cool blue tones, nighttime' },
  { id: 'gl_6', categoryId: 'gen_lighting', label: 'Luz Volumétrica', value: 'volumetric lighting, god rays' },
  { id: 'gl_7', categoryId: 'gen_lighting', label: 'Baja Iluminación', value: 'low key lighting, dramatic shadows' },

  // Cámara / Composición
  { id: 'gc_1', categoryId: 'gen_camera', label: 'Plano General', value: 'wide angle shot, expansive view' },
  { id: 'gc_2', categoryId: 'gen_camera', label: 'Primer Plano', value: 'close up shot, macro photography' },
  { id: 'gc_3', categoryId: 'gen_camera', label: 'Vista de Pájaro', value: 'bird\'s eye view, looking down from above' },
  { id: 'gc_4', categoryId: 'gen_camera', label: 'Vista de Gusano', value: 'worm\'s eye view, looking up from below' },
  { id: 'gc_5', categoryId: 'gen_camera', label: 'Simetría', value: 'perfect symmetry, centered composition' },
  { id: 'gc_6', categoryId: 'gen_camera', label: 'Regla de los Tercios', value: 'rule of thirds composition' },
  { id: 'gc_7', categoryId: 'gen_camera', label: 'Profundidad de Campo', value: 'shallow depth of field, blurred background (bokeh)' },

  // Atmósfera / Mood
  { id: 'gm_1', categoryId: 'gen_mood', label: 'Épico / Majestuoso', value: 'epic, majestic, awe-inspiring atmosphere' },
  { id: 'gm_2', categoryId: 'gen_mood', label: 'Misterioso / Oscuro', value: 'mysterious, dark, eerie mood' },
  { id: 'gm_3', categoryId: 'gen_mood', label: 'Tranquilo / Pacífico', value: 'peaceful, tranquil, serene atmosphere' },
  { id: 'gm_4', categoryId: 'gen_mood', label: 'Caótico / Dinámico', value: 'chaotic, dynamic, high energy' },
  { id: 'gm_5', categoryId: 'gen_mood', label: 'Melancólico', value: 'melancholic, nostalgic mood' },
  { id: 'gm_6', categoryId: 'gen_mood', label: 'Alegre / Vibrante', value: 'cheerful, vibrant, uplifting atmosphere' },

  // Paleta de Color
  { id: 'gco_1', categoryId: 'gen_color', label: 'Colores Pastel', value: 'pastel color palette, soft tones' },
  { id: 'gco_2', categoryId: 'gen_color', label: 'Blanco y Negro', value: 'black and white, monochrome' },
  { id: 'gco_3', categoryId: 'gen_color', label: 'Tonos Cálidos', value: 'warm color palette, reds, oranges, yellows' },
  { id: 'gco_4', categoryId: 'gen_color', label: 'Tonos Fríos', value: 'cool color palette, blues, greens, purples' },
  { id: 'gco_5', categoryId: 'gen_color', label: 'Alto Contraste', value: 'high contrast colors, vivid' },
  { id: 'gco_6', categoryId: 'gen_color', label: 'Tonos Tierra', value: 'earth tones, muted natural colors' },

  // Nivel de Detalle
  { id: 'gd_1', categoryId: 'gen_details', label: 'Ultra Detallado', value: 'ultra-detailed, intricate details, 8k, highly complex' },
  { id: 'gd_2', categoryId: 'gen_details', label: 'Minimalista', value: 'minimalist, simple, clean lines, uncluttered' },
  { id: 'gd_3', categoryId: 'gen_details', label: 'Abstracto', value: 'abstract, non-representational forms' },
  { id: 'gd_4', categoryId: 'gen_details', label: 'Texturizado', value: 'rich textures, tactile surfaces' },

  // Calidades de Imagen (General)
  { id: 'gq_1', categoryId: 'gen_quality', label: 'Mala Calidad', value: 'low quality, blurry, pixelated' },
  { id: 'gq_2', categoryId: 'gen_quality', label: 'Media Calidad', value: 'standard quality, clear' },
  { id: 'gq_3', categoryId: 'gen_quality', label: 'Alta Calidad', value: 'high quality, sharp focus, detailed' },
  { id: 'gq_4', categoryId: 'gen_quality', label: '4K', value: '4k resolution, ultra high definition' },
  { id: 'gq_5', categoryId: 'gen_quality', label: '8K', value: '8k resolution, extreme detail' },
  { id: 'gq_6', categoryId: 'gen_quality', label: 'Piel Plástico Perfecta', value: 'perfect plastic skin, flawless airbrushed texture, AI aesthetic' },
  { id: 'gq_7', categoryId: 'gen_quality', label: 'Masterpiece', value: 'masterpiece, best quality, award winning' },
  { id: 'gq_8', categoryId: 'gen_quality', label: 'HDR', value: 'high dynamic range, vibrant lighting' },
];

export const ALL_CATEGORIES = [...INFLUENCER_CATEGORIES, ...GENERAL_CATEGORIES];

export const INFLUENCER_BLOCKS: Block[] = [
  // Resultado Visual
  { id: 'res_1', categoryId: 'result', label: 'Casual espontáneo', value: 'casual spontaneous' },
  { id: 'res_2', categoryId: 'result', label: 'Selfie natural', value: 'natural selfie' },
  { id: 'res_3', categoryId: 'result', label: 'Editorial de revista', value: 'magazine editorial' },
  { id: 'res_4', categoryId: 'result', label: 'Estudio profesional', value: 'professional studio' },
  { id: 'res_5', categoryId: 'result', label: 'Cinematic', value: 'cinematic' },
  { id: 'res_6', categoryId: 'result', label: 'Aesthetic', value: 'aesthetic' },
  { id: 'res_7', categoryId: 'result', label: 'Film grain', value: 'film grain' },
  { id: 'res_8', categoryId: 'result', label: 'Comercial de producto', value: 'product commercial' },
  { id: 'res_9', categoryId: 'result', label: 'Retrato íntimo', value: 'intimate portrait' },
  { id: 'res_10', categoryId: 'result', label: 'Lifestyle urbano', value: 'urban lifestyle' },
  { id: 'res_11', categoryId: 'result', label: 'Polaroid vintage', value: 'vintage polaroid photo' },
  { id: 'res_12', categoryId: 'result', label: 'Cámara desechable', value: 'disposable camera aesthetic' },
  { id: 'res_13', categoryId: 'result', label: 'Fotografía callejera', value: 'street photography' },
  { id: 'res_14', categoryId: 'result', label: 'Alta costura', value: 'haute couture fashion photography' },
  { id: 'res_15', categoryId: 'result', label: 'Cyberpunk', value: 'cyberpunk aesthetic' },
  { id: 'res_16', categoryId: 'result', label: 'Fantasía oscura', value: 'dark fantasy aesthetic' },

  // Enfoque Principal
  { id: 'foc_1', categoryId: 'focus', label: 'Selfie', value: 'selfie focus, subject is the main subject' },
  { id: 'foc_2', categoryId: 'focus', label: 'Enfoque de rostro', value: 'face focus, close up on the face' },
  { id: 'foc_3', categoryId: 'focus', label: 'Enfoque de pies', value: 'feet focus, feet are the main subject' },
  { id: 'foc_4', categoryId: 'focus', label: 'Enfoque de cuello', value: 'neck focus' },
  { id: 'foc_5', categoryId: 'focus', label: 'Enfoque del entorno', value: 'environment focus, subject is small in the frame' },
  { id: 'foc_6', categoryId: 'focus', label: 'Enfoque de gesto', value: 'gesture focus, focusing on a specific hand or facial gesture' },
  { id: 'foc_7', categoryId: 'focus', label: 'Interacción con fondo', value: 'focus on interaction with the background' },
  { id: 'foc_8', categoryId: 'focus', label: 'Enfoque en labios', value: 'close up focus on lips' },
  { id: 'foc_9', categoryId: 'focus', label: 'Enfoque en ojos', value: 'close up focus on eyes' },
  { id: 'foc_10', categoryId: 'focus', label: 'Enfoque en manos', value: 'close up focus on hands' },
  { id: 'foc_11', categoryId: 'focus', label: 'Enfoque en silueta', value: 'focus on body silhouette' },

  // Tipo de Escena
  { id: 'sce_1', categoryId: 'scene', label: 'En recámara', value: 'in a cozy bedroom' },
  { id: 'sce_2', categoryId: 'scene', label: 'En cama', value: 'in bed' },
  { id: 'sce_3', categoryId: 'scene', label: 'En cocina', value: 'in a kitchen' },
  { id: 'sce_4', categoryId: 'scene', label: 'En la calle', value: 'on the street' },
  { id: 'sce_5', categoryId: 'scene', label: 'En concierto', value: 'at a concert' },
  { id: 'sce_6', categoryId: 'scene', label: 'En escuela', value: 'at school' },
  { id: 'sce_7', categoryId: 'scene', label: 'Fondo liso', value: 'solid background' },
  { id: 'sce_8', categoryId: 'scene', label: 'Fondo de contraste', value: 'high contrast background' },
  { id: 'sce_9', categoryId: 'scene', label: 'Interior cálido', value: 'warm interior' },
  { id: 'sce_10', categoryId: 'scene', label: 'Exterior cotidiano', value: 'everyday exterior' },
  { id: 'sce_11', categoryId: 'scene', label: 'En la playa', value: 'at the beach' },
  { id: 'sce_12', categoryId: 'scene', label: 'En el bosque', value: 'in a dense forest' },
  { id: 'sce_13', categoryId: 'scene', label: 'En un café', value: 'in a cozy coffee shop' },
  { id: 'sce_14', categoryId: 'scene', label: 'En el gimnasio', value: 'at the gym' },
  { id: 'sce_15', categoryId: 'scene', label: 'En un bar', value: 'in a dimly lit bar' },
  { id: 'sce_16', categoryId: 'scene', label: 'En el transporte público', value: 'on public transport, subway or bus' },
  { id: 'sce_17', categoryId: 'scene', label: 'En un jardín botánico', value: 'in a lush botanical garden' },
  { id: 'sce_18', categoryId: 'scene', label: 'En una biblioteca antigua', value: 'in an old library with wooden shelves' },
  { id: 'sce_19', categoryId: 'scene', label: 'En una azotea (rooftop)', value: 'on a city rooftop at sunset' },
  { id: 'sce_20', categoryId: 'scene', label: 'En un estudio de arte', value: 'in a messy art studio with canvases' },
  { id: 'sce_21', categoryId: 'scene', label: 'En un centro comercial', value: 'in a modern shopping mall' },
  { id: 'sce_22', categoryId: 'scene', label: 'En un parque de diversiones', value: 'at an amusement park with lights' },
  { id: 'sce_23', categoryId: 'scene', label: 'En un balcón', value: 'on a balcony overlooking the city' },
  { id: 'sce_24', categoryId: 'scene', label: 'En un elevador', value: 'inside a modern elevator' },

  // Ambientación
  { id: 'env_1', categoryId: 'environment', label: 'Madrugada', value: 'early morning, dawn' },
  { id: 'env_2', categoryId: 'environment', label: 'Día', value: 'daytime, bright daylight' },
  { id: 'env_3', categoryId: 'environment', label: 'Tarde', value: 'late afternoon' },
  { id: 'env_4', categoryId: 'environment', label: 'Noche', value: 'nighttime, dark' },
  { id: 'env_5', categoryId: 'environment', label: 'Variaciones interiores', value: 'indoor ambient variations' },
  { id: 'env_6', categoryId: 'environment', label: 'Lluvioso', value: 'rainy weather, wet surfaces' },
  { id: 'env_7', categoryId: 'environment', label: 'Nublado', value: 'overcast, cloudy sky' },
  { id: 'env_8', categoryId: 'environment', label: 'Nevado', value: 'snowy environment, winter' },
  { id: 'env_9', categoryId: 'environment', label: 'Niebla densa', value: 'dense fog, mysterious atmosphere' },
  { id: 'env_10', categoryId: 'environment', label: 'Tormenta eléctrica', value: 'thunderstorm, lightning in the distance' },
  { id: 'env_11', categoryId: 'environment', label: 'Atardecer púrpura', value: 'purple and orange sunset sky' },
  { id: 'env_12', categoryId: 'environment', label: 'Luz de neblina matutina', value: 'soft morning mist and sunbeams' },
  { id: 'env_13', categoryId: 'environment', label: 'Calor sofocante', value: 'heat haze, shimmering air' },
  { id: 'env_14', categoryId: 'environment', label: 'Viento fuerte', value: 'windy atmosphere, dust motes' },

  // Acción / Situación
  { id: 'act_1', categoryId: 'action', label: 'Caminando', value: 'walking' },
  { id: 'act_2', categoryId: 'action', label: 'Posando solo/a', value: 'posing alone' },
  { id: 'act_3', categoryId: 'action', label: 'Comiendo', value: 'eating' },
  { id: 'act_4', categoryId: 'action', label: 'Reunión con amigos', value: 'hanging out with friends' },
  { id: 'act_5', categoryId: 'action', label: 'Tomándose selfie', value: 'taking a selfie' },
  { id: 'act_6', categoryId: 'action', label: 'Mostrando producto', value: 'showing a product' },
  { id: 'act_7', categoryId: 'action', label: 'Sentada/o descansando', value: 'sitting and resting' },
  { id: 'act_8', categoryId: 'action', label: 'Interactuando con objeto', value: 'interacting with an object' },
  { id: 'act_9', categoryId: 'action', label: 'Momento robado', value: 'candid stolen moment' },
  { id: 'act_10', categoryId: 'action', label: 'Bailando', value: 'dancing energetically' },
  { id: 'act_11', categoryId: 'action', label: 'Leyendo un libro', value: 'reading a book' },
  { id: 'act_12', categoryId: 'action', label: 'Bebiendo café', value: 'drinking coffee' },
  { id: 'act_13', categoryId: 'action', label: 'Mirando el celular', value: 'looking at smartphone' },
  { id: 'act_14', categoryId: 'action', label: 'Acomodándose el cabello', value: 'adjusting hair' },
  { id: 'act_15', categoryId: 'action', label: 'Haciendo ejercicio', value: 'working out, intense exercise' },
  { id: 'act_16', categoryId: 'action', label: 'Escuchando música', value: 'listening to music with headphones' },
  { id: 'act_17', categoryId: 'action', label: 'Pintando/Dibujando', value: 'painting on a canvas' },
  { id: 'act_18', categoryId: 'action', label: 'Cocinando', value: 'cooking a meal' },
  { id: 'act_19', categoryId: 'action', label: 'Hablando por teléfono', value: 'talking on the phone' },
  { id: 'act_20', categoryId: 'action', label: 'Meditando', value: 'meditating peacefully' },
  { id: 'act_21', categoryId: 'action', label: 'Tomando fotos', value: 'taking photos with a professional camera' },
  { id: 'act_22', categoryId: 'action', label: 'Esperando el bus', value: 'waiting at a bus stop' },
  { id: 'act_23', categoryId: 'action', label: 'Maquillándose', value: 'applying makeup in front of a mirror' },
  { id: 'act_24', categoryId: 'action', label: 'Susurrando', value: 'whispering into someone\'s ear' },

  // Movimiento
  { id: 'mov_1', categoryId: 'movement', label: 'Completamente quieta', value: 'completely still, posing' },
  { id: 'mov_2', categoryId: 'movement', label: 'Caminando (motion)', value: 'walking motion' },
  { id: 'mov_3', categoryId: 'movement', label: 'Ligero motion blur', value: 'slight motion blur' },
  { id: 'mov_4', categoryId: 'movement', label: 'Muy movida (corriendo)', value: 'heavy motion blur, running or escaping' },
  { id: 'mov_5', categoryId: 'movement', label: 'Rotando ángulo', value: 'rotating camera angle, dynamic movement' },
  { id: 'mov_6', categoryId: 'movement', label: 'Zoom in/out', value: 'zoom burst effect' },
  { id: 'mov_7', categoryId: 'movement', label: 'Luces movidas (noche)', value: 'light trails, night motion' },
  { id: 'mov_8', categoryId: 'movement', label: 'Cabello al viento', value: 'hair blowing in the wind' },
  { id: 'mov_9', categoryId: 'movement', label: 'Ropa ondeando', value: 'clothes fluttering in the wind' },
  { id: 'mov_10', categoryId: 'movement', label: 'Saltando', value: 'jumping in the air, frozen motion' },
  { id: 'mov_11', categoryId: 'movement', label: 'Caída libre', value: 'falling through the air' },
  { id: 'mov_12', categoryId: 'movement', label: 'Giro rápido', value: 'spinning around quickly' },

  // Gesticulación
  { id: 'ges_1', categoryId: 'gesticulation', label: 'Expresión acorde', value: 'expression naturally adapted to the action' },
  { id: 'ges_2', categoryId: 'gesticulation', label: 'Manos creíbles', value: 'hands interacting naturally' },
  { id: 'ges_3', categoryId: 'gesticulation', label: 'Postura natural', value: 'natural posture' },
  { id: 'ges_4', categoryId: 'gesticulation', label: 'Mirada a cámara', value: 'looking directly at the camera' },
  { id: 'ges_5', categoryId: 'gesticulation', label: 'Mirada perdida', value: 'looking away thoughtfully' },
  { id: 'ges_6', categoryId: 'gesticulation', label: 'Sonrisa amplia', value: 'wide happy smile' },
  { id: 'ges_7', categoryId: 'gesticulation', label: 'Expresión seria', value: 'serious, stoic expression' },
  { id: 'ges_8', categoryId: 'gesticulation', label: 'Guiño', value: 'winking one eye' },
  { id: 'ges_9', categoryId: 'gesticulation', label: 'Mordiéndose el labio', value: 'biting lip gently' },
  { id: 'ges_10', categoryId: 'gesticulation', label: 'Sorpresa', value: 'surprised expression' },
  { id: 'ges_11', categoryId: 'gesticulation', label: 'Enojo sutil', value: 'subtle angry expression, furrowed brow' },
  { id: 'ges_12', categoryId: 'gesticulation', label: 'Tristeza melancólica', value: 'melancholic, sad expression' },
  { id: 'ges_13', categoryId: 'gesticulation', label: 'Risa incontrolable', value: 'laughing uncontrollably' },
  { id: 'ges_14', categoryId: 'gesticulation', label: 'Aburrimiento', value: 'bored, uninterested expression' },
  { id: 'ges_15', categoryId: 'gesticulation', label: 'Seducción', value: 'seductive, alluring gaze' },
  { id: 'ges_16', categoryId: 'gesticulation', label: 'Concentración', value: 'deep concentration, focused eyes' },

  // Partes Expuestas
  { id: 'exp_1', categoryId: 'exposed_body', label: 'Brazos visibles', value: 'bare arms visible, realistic skin texture' },
  { id: 'exp_2', categoryId: 'exposed_body', label: 'Abdomen (ombliguera)', value: 'bare midriff, visible abdomen, crop top style' },
  { id: 'exp_3', categoryId: 'exposed_body', label: 'Piernas visibles', value: 'bare legs visible, realistic skin texture' },
  { id: 'exp_4', categoryId: 'exposed_body', label: 'Muslos visibles', value: 'bare thighs visible' },
  { id: 'exp_5', categoryId: 'exposed_body', label: 'Pies visibles', value: 'bare feet visible, detailed' },
  { id: 'exp_6', categoryId: 'exposed_body', label: 'Manos visibles', value: 'hands visible, realistic skin texture' },
  { id: 'exp_7', categoryId: 'exposed_body', label: 'Espalda visible', value: 'bare back visible, realistic skin texture' },
  { id: 'exp_8', categoryId: 'exposed_body', label: 'Rodillas visibles', value: 'bare knees visible' },
  { id: 'exp_9', categoryId: 'exposed_body', label: 'Hombros visibles', value: 'bare shoulders visible' },
  { id: 'exp_10', categoryId: 'exposed_body', label: 'Codos visibles', value: 'bare elbows visible' },
  { id: 'exp_11', categoryId: 'exposed_body', label: 'Cuello visible', value: 'bare neck visible' },
  { id: 'exp_12', categoryId: 'exposed_body', label: 'Parte superior sin ropa', value: 'topless, bare upper body, realistic skin texture', isNsfw: true },
  { id: 'exp_13', categoryId: 'exposed_body', label: 'Parte inferior sin ropa', value: 'bottomless, bare lower body, realistic skin texture', isNsfw: true },
  { id: 'exp_14', categoryId: 'exposed_body', label: 'Completamente sin ropa', value: 'completely nude, full body realistic skin texture', isNsfw: true },
  { id: 'exp_15', categoryId: 'exposed_body', label: 'Pezones visibles', value: 'visible nipples', isNsfw: true },
  { id: 'exp_16', categoryId: 'exposed_body', label: 'Vagina visible', value: 'visible vagina', isNsfw: true },
  { id: 'exp_17', categoryId: 'exposed_body', label: 'Pene visible', value: 'visible penis', isNsfw: true },
  { id: 'exp_18', categoryId: 'exposed_body', label: 'Glúteos expuestos', value: 'bare buttocks exposed', isNsfw: true },

  // Cámara / Ángulo
  { id: 'cam_1', categoryId: 'camera', label: 'Primer plano', value: 'close up shot' },
  { id: 'cam_2', categoryId: 'camera', label: 'Medio cuerpo', value: 'medium shot' },
  { id: 'cam_3', categoryId: 'camera', label: 'Cuerpo completo', value: 'full body shot' },
  { id: 'cam_4', categoryId: 'camera', label: 'Picado', value: 'high angle' },
  { id: 'cam_5', categoryId: 'camera', label: 'Contrapicado', value: 'low angle' },
  { id: 'cam_6', categoryId: 'camera', label: 'Selfie angle', value: 'selfie angle' },
  { id: 'cam_7', categoryId: 'camera', label: 'Ángulo lateral', value: 'side angle' },
  { id: 'cam_8', categoryId: 'camera', label: 'Composición centrada', value: 'centered composition' },
  { id: 'cam_9', categoryId: 'camera', label: 'Estilo paparazzi', value: 'paparazzi style' },
  { id: 'cam_10', categoryId: 'camera', label: 'Vista de pájaro', value: 'bird\'s eye view' },
  { id: 'cam_11', categoryId: 'camera', label: 'Vista de gusano', value: 'worm\'s eye view' },
  { id: 'cam_12', categoryId: 'camera', label: 'Ángulo holandés', value: 'dutch angle, tilted camera' },
  { id: 'cam_13', categoryId: 'camera', label: 'Plano detalle', value: 'extreme close up, macro shot' },
  { id: 'cam_14', categoryId: 'camera', label: 'Desde atrás', value: 'shot from behind' },
  { id: 'cam_15', categoryId: 'camera', label: 'Ángulo de hombro', value: 'over-the-shoulder shot' },
  { id: 'cam_16', categoryId: 'camera', label: 'Gran plano general', value: 'extreme wide shot' },

  // Lentes / Parámetros
  { id: 'len_1', categoryId: 'lens', label: '24mm', value: 'shot on 24mm lens' },
  { id: 'len_2', categoryId: 'lens', label: '35mm', value: 'shot on 35mm lens' },
  { id: 'len_3', categoryId: 'lens', label: '50mm', value: 'shot on 50mm lens' },
  { id: 'len_4', categoryId: 'lens', label: '85mm', value: 'shot on 85mm lens' },
  { id: 'len_5', categoryId: 'lens', label: 'Teleobjetivo', value: 'telephoto lens' },
  { id: 'len_6', categoryId: 'lens', label: 'Gran angular', value: 'wide angle lens' },
  { id: 'len_7', categoryId: 'lens', label: 'f/1.8', value: 'f/1.8 aperture' },
  { id: 'len_8', categoryId: 'lens', label: 'Fondo desenfocado', value: 'shallow depth of field, blurred background' },
  { id: 'len_9', categoryId: 'lens', label: 'Nitidez de estudio', value: 'studio sharpness' },
  { id: 'len_10', categoryId: 'lens', label: 'Ojo de pez', value: 'fisheye lens effect' },
  { id: 'len_11', categoryId: 'lens', label: 'Lente anamórfico', value: 'anamorphic lens flare' },
  { id: 'len_12', categoryId: 'lens', label: 'Cámara iPhone', value: 'shot on iPhone camera, natural smartphone photography' },
  { id: 'len_13', categoryId: 'lens', label: 'Lente macro', value: 'macro lens, extreme detail' },
  { id: 'len_14', categoryId: 'lens', label: 'Filtro vintage', value: 'vintage lens filter, soft edges' },

  // Iluminación
  { id: 'lig_1', categoryId: 'lighting', label: 'Luz natural', value: 'natural lighting' },
  { id: 'lig_2', categoryId: 'lighting', label: 'Luz de ventana', value: 'window light' },
  { id: 'lig_3', categoryId: 'lighting', label: 'Golden hour', value: 'golden hour lighting' },
  { id: 'lig_4', categoryId: 'lighting', label: 'Luz artificial', value: 'artificial lighting' },
  { id: 'lig_5', categoryId: 'lighting', label: 'Luz dura', value: 'hard light' },
  { id: 'lig_6', categoryId: 'lighting', label: 'Luz suave', value: 'soft diffused light' },
  { id: 'lig_7', categoryId: 'lighting', label: 'Neón de color', value: 'colorful neon lighting' },
  { id: 'lig_8', categoryId: 'lighting', label: 'Contraluz', value: 'backlighting' },
  { id: 'lig_9', categoryId: 'lighting', label: 'Iluminación editorial', value: 'editorial lighting setup' },
  { id: 'lig_10', categoryId: 'lighting', label: 'Luz de luna', value: 'moonlight illumination' },
  { id: 'lig_11', categoryId: 'lighting', label: 'Luz de velas', value: 'candlelight, warm glow' },
  { id: 'lig_12', categoryId: 'lighting', label: 'Luz de flash directo', value: 'direct flash photography' },
  { id: 'lig_13', categoryId: 'lighting', label: 'Iluminación dramática', value: 'dramatic chiaroscuro lighting' },
  { id: 'lig_14', categoryId: 'lighting', label: 'Luz de discoteca', value: 'disco lights, strobes, colorful beams' },
  { id: 'lig_15', categoryId: 'lighting', label: 'Luz de atardecer', value: 'warm sunset light' },
  { id: 'lig_16', categoryId: 'lighting', label: 'Luz volumétrica', value: 'volumetric lighting, god rays' },

  // Realismo
  { id: 'rea_1', categoryId: 'realism', label: 'Poros visibles', value: 'visible skin pores' },
  { id: 'rea_2', categoryId: 'realism', label: 'Textura natural', value: 'natural skin texture' },
  { id: 'rea_3', categoryId: 'realism', label: 'Microimperfecciones', value: 'facial micro-details and imperfections' },
  { id: 'rea_4', categoryId: 'realism', label: 'Arrugas sutiles', value: 'subtle wrinkles' },
  { id: 'rea_5', categoryId: 'realism', label: 'Cabello real', value: 'natural hair strands' },
  { id: 'rea_6', categoryId: 'realism', label: 'Pliegues de ropa', value: 'believable fabric folds' },
  { id: 'rea_7', categoryId: 'realism', label: 'Sombras naturales', value: 'true-to-life ambient shadows' },
  { id: 'rea_8', categoryId: 'realism', label: 'Piel realista (cuerpo)', value: 'realistic skin texture on the entire body, not just the face' },
  { id: 'rea_9', categoryId: 'realism', label: 'Pecas y lunares', value: 'natural freckles and moles' },
  { id: 'rea_10', categoryId: 'realism', label: 'Sudor ligero', value: 'light sweat or moisture on skin' },
  { id: 'rea_11', categoryId: 'realism', label: 'Vello corporal sutil', value: 'subtle natural body hair' },
  { id: 'rea_12', categoryId: 'realism', label: 'Cicatrices sutiles', value: 'subtle realistic scars' },
  { id: 'rea_13', categoryId: 'realism', label: 'Venas visibles', value: 'subtle visible veins under skin' },

  // Outfit / Styling
  { id: 'out_1', categoryId: 'outfit', label: 'Dark outfit', value: 'dark outfit' },
  { id: 'out_2', categoryId: 'outfit', label: 'Streetwear', value: 'streetwear' },
  { id: 'out_3', categoryId: 'outfit', label: 'Casual', value: 'casual wear' },
  { id: 'out_4', categoryId: 'outfit', label: 'Elegante', value: 'elegant attire' },
  { id: 'out_5', categoryId: 'outfit', label: 'Minimalista', value: 'minimalist clothing' },
  { id: 'out_6', categoryId: 'outfit', label: 'Crop top negro', value: 'black crop top' },
  { id: 'out_7', categoryId: 'outfit', label: 'Vestido', value: 'dress' },
  { id: 'out_8', categoryId: 'outfit', label: 'Tattoos', value: 'tattoos' },
  { id: 'out_9', categoryId: 'outfit', label: 'Maquillaje oscuro', value: 'dark eye makeup' },
  { id: 'out_10', categoryId: 'outfit', label: 'Ropa deportiva', value: 'sportswear, athletic clothing' },
  { id: 'out_11', categoryId: 'outfit', label: 'Traje de baño', value: 'swimsuit, bikini' },
  { id: 'out_12', categoryId: 'outfit', label: 'Lencería', value: 'lingerie', isNsfw: true },
  { id: 'out_13', categoryId: 'outfit', label: 'Ropa de invierno', value: 'winter clothing, heavy coat' },
  { id: 'out_14', categoryId: 'outfit', label: 'Gafas de sol', value: 'wearing sunglasses' },
  { id: 'out_15', categoryId: 'outfit', label: 'Ropa transparente', value: 'see-through clothing, sheer fabric', isNsfw: true },
  { id: 'out_16', categoryId: 'outfit', label: 'Estilo gótico', value: 'gothic fashion style' },
  { id: 'out_17', categoryId: 'outfit', label: 'Ropa de cuero', value: 'leather clothing' },
  { id: 'out_18', categoryId: 'outfit', label: 'Uniforme escolar', value: 'school uniform' },
  { id: 'out_19', categoryId: 'outfit', label: 'Pijama', value: 'pajamas, sleepwear' },
  { id: 'out_20', categoryId: 'outfit', label: 'Ropa de seda', value: 'silk clothing, smooth texture' },

  // Maquillaje
  { id: 'mak_1', categoryId: 'makeup', label: 'Natural / No-makeup', value: 'no-makeup makeup look, natural skin' },
  { id: 'mak_2', categoryId: 'makeup', label: 'E-girl', value: 'e-girl makeup, heavy blush, winged eyeliner' },
  { id: 'mak_3', categoryId: 'makeup', label: 'Solo gloss', value: 'clear lip gloss only, bare face' },
  { id: 'mak_4', categoryId: 'makeup', label: 'Delineado gráfico', value: 'graphic eyeliner, sharp wings' },
  { id: 'mak_5', categoryId: 'makeup', label: 'Smokey eye', value: 'dark smokey eye makeup' },
  { id: 'mak_6', categoryId: 'makeup', label: 'Labios rojos', value: 'classic red lipstick' },
  { id: 'mak_7', categoryId: 'makeup', label: 'Maquillaje Drag', value: 'drag queen makeup, exaggerated features, heavy contour' },
  { id: 'mak_8', categoryId: 'makeup', label: 'Pecas falsas', value: 'faux freckles' },
  { id: 'mak_9', categoryId: 'makeup', label: 'Sombra neón', value: 'neon eyeshadow' },
  { id: 'mak_10', categoryId: 'makeup', label: 'Soft glam', value: 'soft glam makeup, glowing skin' },
  { id: 'mak_11', categoryId: 'makeup', label: 'Gótico', value: 'goth makeup, black lipstick, pale skin' },
  { id: 'mak_12', categoryId: 'makeup', label: 'Euphoria style', value: 'euphoria makeup, rhinestones, glitter' },
  { id: 'mak_13', categoryId: 'makeup', label: 'Maquillaje de fantasía', value: 'fantasy makeup, artistic patterns' },

  // Paleta / Color
  { id: 'col_1', categoryId: 'color', label: 'Neutros', value: 'neutral color palette' },
  { id: 'col_2', categoryId: 'color', label: 'Oscuros', value: 'dark color palette' },
  { id: 'col_3', categoryId: 'color', label: 'Cálidos', value: 'warm color palette' },
  { id: 'col_4', categoryId: 'color', label: 'Fríos', value: 'cold color palette' },
  { id: 'col_5', categoryId: 'color', label: 'Monocromático', value: 'monochromatic' },
  { id: 'col_6', categoryId: 'color', label: 'Contraste alto', value: 'high contrast colors' },
  { id: 'col_7', categoryId: 'color', label: 'Acentos rojos', value: 'red accents' },
  { id: 'col_8', categoryId: 'color', label: 'Negro total', value: 'all black palette' },
  { id: 'col_9', categoryId: 'color', label: 'Tonos pastel', value: 'pastel color palette' },
  { id: 'col_10', categoryId: 'color', label: 'Blanco y negro', value: 'black and white photography' },
  { id: 'col_11', categoryId: 'color', label: 'Saturación alta', value: 'vibrant, highly saturated colors' },
  { id: 'col_12', categoryId: 'color', label: 'Tonos tierra', value: 'earth tones, brown and green palette' },
  { id: 'col_13', categoryId: 'color', label: 'Dorado y negro', value: 'gold and black color scheme' },
  { id: 'col_14', categoryId: 'color', label: 'Azul eléctrico', value: 'electric blue accents' },

  // Fondo y Props
  { id: 'pro_1', categoryId: 'props', label: 'Tapete circular', value: 'circular rug on the floor' },
  { id: 'pro_2', categoryId: 'props', label: 'Espejo', value: 'mirror' },
  { id: 'pro_3', categoryId: 'props', label: 'Posters', value: 'posters on the wall' },
  { id: 'pro_4', categoryId: 'props', label: 'Cama desordenada', value: 'aesthetic messy bed' },
  { id: 'pro_5', categoryId: 'props', label: 'Lámpara cálida', value: 'warm lamp' },
  { id: 'pro_6', categoryId: 'props', label: 'Celular', value: 'smartphone' },
  { id: 'pro_7', categoryId: 'props', label: 'Maquillaje', value: 'makeup items' },
  { id: 'pro_8', categoryId: 'props', label: 'Plantas de interior', value: 'indoor plants, monstera' },
  { id: 'pro_9', categoryId: 'props', label: 'Taza de café', value: 'coffee mug' },
  { id: 'pro_10', categoryId: 'props', label: 'Libros apilados', value: 'stack of books' },
  { id: 'pro_11', categoryId: 'props', label: 'Instrumento musical', value: 'musical instrument, guitar' },
  { id: 'pro_12', categoryId: 'props', label: 'Coche deportivo', value: 'sports car in the background' },
  { id: 'pro_13', categoryId: 'props', label: 'Laptop abierta', value: 'open laptop on a desk' },
  { id: 'pro_14', categoryId: 'props', label: 'Auriculares grandes', value: 'large over-ear headphones' },
  { id: 'pro_15', categoryId: 'props', label: 'Cámara vintage', value: 'vintage film camera' },
  { id: 'pro_16', categoryId: 'props', label: 'Mascota (perro/gato)', value: 'a cute pet nearby' },
  { id: 'pro_17', categoryId: 'props', label: 'Comida rápida', value: 'fast food, pizza or burger' },
  { id: 'pro_18', categoryId: 'props', label: 'Bebida energética', value: 'energy drink can' },
  { id: 'pro_19', categoryId: 'props', label: 'Mochila', value: 'backpack' },
  { id: 'pro_20', categoryId: 'props', label: 'Skateboard', value: 'skateboard leaning against a wall' },


  // Intención
  { id: 'int_1', categoryId: 'intention', label: 'Para redes sociales', value: 'social media feel' },
  { id: 'int_2', categoryId: 'intention', label: 'Para marca', value: 'brand photography' },
  { id: 'int_3', categoryId: 'intention', label: 'Campaña casual', value: 'casual campaign' },
  { id: 'int_4', categoryId: 'intention', label: 'Imagen aspiracional', value: 'aspirational image' },
  { id: 'int_5', categoryId: 'intention', label: 'Lookbook', value: 'fashion lookbook' },
  { id: 'int_6', categoryId: 'intention', label: 'Fotografía documental', value: 'documentary photography style' },
  { id: 'int_7', categoryId: 'intention', label: 'Arte conceptual', value: 'conceptual art photography' },
  { id: 'int_8', categoryId: 'intention', label: 'Póster de película', value: 'movie poster aesthetic' },

  // Detalles del Cuerpo
  { id: 'bod_1', categoryId: 'body_details', label: 'Altura: Alta', value: 'tall height, long limbs' },
  { id: 'bod_2', categoryId: 'body_details', label: 'Altura: Media', value: 'average height' },
  { id: 'bod_3', categoryId: 'body_details', label: 'Altura: Baja', value: 'short height, petite' },
  { id: 'bod_4', categoryId: 'body_details', label: 'Piernas alargadas', value: 'long slender legs' },
  { id: 'bod_5', categoryId: 'body_details', label: 'Tamaño de Busto', value: 'specific bust size' },
  { id: 'bod_6', categoryId: 'body_details', label: 'Piel de porcelana', value: 'pale porcelain skin, smooth and flawless' },
  { id: 'bod_7', categoryId: 'body_details', label: 'Piel humectada', value: 'moisturized glowing skin, dewy texture' },
  { id: 'bod_8', categoryId: 'body_details', label: 'Piel seca', value: 'dry skin texture, matte finish' },
  { id: 'bod_9', categoryId: 'body_details', label: 'Piel natural/sana', value: 'natural healthy skin texture' },
  { id: 'bod_10', categoryId: 'body_details', label: 'Enrojecimiento natural (Pies)', value: 'natural pinkish redness on feet and soles' },
  { id: 'bod_11', categoryId: 'body_details', label: 'Enrojecimiento natural (Rodillas)', value: 'natural pinkish redness on knees' },
  { id: 'bod_12', categoryId: 'body_details', label: 'Enrojecimiento natural (Mejillas)', value: 'natural rosy cheeks' },
  { id: 'bod_13', categoryId: 'body_details', label: 'Detalle de nacimiento', value: 'unique birthmark or skin detail' },
  { id: 'bod_14', categoryId: 'body_details', label: 'Piel bronceada', value: 'sun-kissed tanned skin' },
  { id: 'bod_15', categoryId: 'body_details', label: 'Piel pecosa (cuerpo)', value: 'freckles scattered across the body' },
  { id: 'bod_16', categoryId: 'body_details', label: 'Complexión atlética', value: 'athletic toned body build' },
  { id: 'bod_17', categoryId: 'body_details', label: 'Complexión delgada', value: 'slender slim body build' },
  { id: 'bod_18', categoryId: 'body_details', label: 'Complexión curvilínea', value: 'curvy hourglass body shape' },
  { id: 'bod_19', categoryId: 'body_details', label: 'Piel pálida', value: 'fair pale skin tone' },
  { id: 'bod_20', categoryId: 'body_details', label: 'Piel morena', value: 'brown skin tone' },
  { id: 'bod_21', categoryId: 'body_details', label: 'Piel oscura', value: 'dark skin tone' },
  { id: 'bod_22', categoryId: 'body_details', label: 'Venas sutiles', value: 'subtle visible blue veins under fair skin' },
  { id: 'bod_23', categoryId: 'body_details', label: 'Cuerpo: Reloj de arena', value: 'hourglass body shape' },
  { id: 'bod_24', categoryId: 'body_details', label: 'Cuerpo: Pera', value: 'pear-shaped body' },
  { id: 'bod_25', categoryId: 'body_details', label: 'Cuerpo: Rectangular', value: 'rectangular body shape' },
  { id: 'bod_26', categoryId: 'body_details', label: 'Piernas: Musculosas', value: 'muscular toned legs' },
  { id: 'bod_27', categoryId: 'body_details', label: 'Piernas: Delgadas', value: 'thin slender legs' },
  { id: 'bod_28', categoryId: 'body_details', label: 'Pies: Arcos altos', value: 'high arched feet' },
  { id: 'bod_29', categoryId: 'body_details', label: 'Pies: Uñas pintadas', value: 'painted toenails, pedicure' },
  { id: 'bod_30', categoryId: 'body_details', label: 'Pies: Suelas rosadas', value: 'pinkish soles of feet' },
  { id: 'bod_31', categoryId: 'body_details', label: 'Detalle: Clavículas marcadas', value: 'prominent collarbones' },
  { id: 'bod_32', categoryId: 'body_details', label: 'Detalle: Espalda definida', value: 'defined back muscles' },
  { id: 'bod_33', categoryId: 'body_details', label: 'Detalle: Manos delicadas', value: 'delicate slender hands' },
  { id: 'bod_34', categoryId: 'body_details', label: 'Detalle: Cuello largo', value: 'long elegant neck' },
  { id: 'bod_35', categoryId: 'body_details', label: 'Piel: Con vello sutil', value: 'subtle natural body hair' },
  { id: 'bod_36', categoryId: 'body_details', label: 'Piel: Con estrías', value: 'realistic stretch marks' },
  { id: 'bod_37', categoryId: 'body_details', label: 'Piel: Con celulitis', value: 'realistic cellulite texture' },

  // Calidades de Imagen (Influencer)
  { id: 'q_1', categoryId: 'quality', label: 'Mala Calidad', value: 'low quality, blurry' },
  { id: 'q_2', categoryId: 'quality', label: 'Media Calidad', value: 'standard quality' },
  { id: 'q_3', categoryId: 'quality', label: 'Alta Calidad', value: 'high quality, sharp' },
  { id: 'q_4', categoryId: 'quality', label: '4K', value: '4k' },
  { id: 'q_5', categoryId: 'quality', label: '8K', value: '8k' },
  { id: 'q_6', categoryId: 'quality', label: 'Piel Plástico Perfecta', value: 'perfect plastic skin, flawless AI texture' },
  { id: 'q_7', categoryId: 'quality', label: 'HD Realista', value: 'realistic HD photography' },
  { id: 'q_8', categoryId: 'quality', label: 'Raw Photo', value: 'unprocessed raw photo, natural' },

  // Restricciones / Negativos
  { id: 'neg_1', categoryId: 'negative', label: 'Evitar manos deformes', value: 'avoid deformed hands' },
  { id: 'neg_2', categoryId: 'negative', label: 'Evitar sobreprocesado', value: 'avoid overprocessed look' },
  { id: 'neg_3', categoryId: 'negative', label: 'Evitar piel plástica', value: 'avoid plastic skin' },
  { id: 'neg_4', categoryId: 'negative', label: 'Evitar poses imposibles', value: 'avoid impossible poses' },
  { id: 'neg_5', categoryId: 'negative', label: 'Evitar expresión vacía', value: 'avoid empty expressions' },
  { id: 'neg_6', categoryId: 'negative', label: 'Evitar texto', value: 'avoid text, watermarks, signatures' },
  { id: 'neg_7', categoryId: 'negative', label: 'Evitar asimetría facial', value: 'avoid facial asymmetry' },
  { id: 'neg_8', categoryId: 'negative', label: 'Evitar censura', value: 'avoid censorship bars or blur', isNsfw: true },
];

import { Preset } from './types';

export const PRESETS: Preset[] = [
  {
    id: 'preset_1',
    label: 'Redes Influencer',
    description: 'Selfie natural, textura de piel, iluminación casual.',
    icon: 'Instagram',
    blockIds: ['res_2', 'rea_1', 'rea_2', 'lig_1', 'cam_6', 'sce_1', 'act_5']
  },
  {
    id: 'preset_2',
    label: 'Estudio Profesional',
    description: 'Iluminación dura, alta costura, fondo liso.',
    icon: 'Camera',
    blockIds: ['res_4', 'lig_5', 'len_4', 'cam_3', 'sce_7', 'out_4']
  },
  {
    id: 'preset_3',
    label: 'Cinematic Nocturno',
    description: 'Luz de neón, lluvia, cyberpunk, 35mm.',
    icon: 'Film',
    blockIds: ['res_5', 'env_4', 'env_6', 'lig_7', 'len_2', 'res_15']
  },
  {
    id: 'preset_4',
    label: 'Vintage Polaroid',
    description: 'Grano de película, flash directo, espontáneo.',
    icon: 'Image',
    blockIds: ['res_11', 'res_7', 'lig_12', 'act_9', 'col_3']
  },
  {
    id: 'preset_5',
    label: 'Boudoir Íntimo (NSFW)',
    description: 'Luz suave, lencería, piel realista, cama.',
    icon: 'Heart',
    blockIds: ['res_9', 'lig_6', 'sce_2', 'out_12', 'exp_12', 'rea_2'],
    isNsfw: true
  }
];

export const ALL_BLOCKS = [...INFLUENCER_BLOCKS, ...GENERAL_BLOCKS];