import { Category, Block } from './types';

export const INFLUENCER_CATEGORIES: Category[] = [
  { id: 'result', label: 'Visual Result', icon: 'Image', color: 'text-blue-400' },
  { id: 'focus', label: 'Main Focus', icon: 'Crosshair', color: 'text-indigo-400' },
  { id: 'scene', label: 'Scene Type', icon: 'MapPin', color: 'text-cyan-400' },
  { id: 'environment', label: 'Environment', icon: 'Cloud', color: 'text-sky-400' },
  { id: 'action', label: 'Action / Situation', icon: 'Activity', color: 'text-teal-400' },
  { id: 'movement', label: 'Movement', icon: 'Wind', color: 'text-emerald-400' },
  { id: 'gesticulation', label: 'Gesticulation', icon: 'Smile', color: 'text-green-400' },
  { id: 'exposed_body', label: 'Exposed Parts', icon: 'User', color: 'text-lime-400' },
  { id: 'camera', label: 'Camera / Angle', icon: 'Camera', color: 'text-yellow-400' },
  { id: 'lens', label: 'Lens / Parameters', icon: 'Aperture', color: 'text-amber-400' },
  { id: 'lighting', label: 'Lighting', icon: 'Sun', color: 'text-orange-400' },
  { id: 'realism', label: 'Realism', icon: 'Eye', color: 'text-red-400' },
  { id: 'outfit', label: 'Outfit / Styling', icon: 'Shirt', color: 'text-rose-400' },
  { id: 'makeup', label: 'Makeup', icon: 'Sparkles', color: 'text-fuchsia-300' },
  { id: 'color', label: 'Palette / Color', icon: 'Palette', color: 'text-pink-400' },
  { id: 'props', label: 'Background & Props', icon: 'Box', color: 'text-fuchsia-400' },
  { id: 'intention', label: 'Intention', icon: 'Target', color: 'text-purple-400' },
  { id: 'body_details', label: 'Body Details', icon: 'User', color: 'text-rose-300' },
  { id: 'quality', label: 'Image Qualities', icon: 'Sparkles', color: 'text-yellow-300' },
  { id: 'negative', label: 'Restrictions', icon: 'ShieldAlert', color: 'text-zinc-400' },
  { id: 'my_prompts', label: 'My Prompts', icon: 'FileText', color: 'text-zinc-400' },
];

export const GENERAL_CATEGORIES: Category[] = [
  { id: 'gen_style', label: 'Artistic Style', icon: 'Palette', color: 'text-pink-400' },
  { id: 'gen_subject', label: 'Main Subject', icon: 'Box', color: 'text-blue-400' },
  { id: 'gen_environment', label: 'Environment / Landscape', icon: 'Map', color: 'text-emerald-400' },
  { id: 'gen_lighting', label: 'Lighting', icon: 'Sun', color: 'text-orange-400' },
  { id: 'gen_camera', label: 'Camera / Composition', icon: 'Camera', color: 'text-yellow-400' },
  { id: 'gen_mood', label: 'Atmosphere / Mood', icon: 'Cloud', color: 'text-purple-400' },
  { id: 'gen_color', label: 'Color Palette', icon: 'Droplet', color: 'text-cyan-400' },
  { id: 'gen_quality', label: 'Image Qualities', icon: 'Sparkles', color: 'text-yellow-300' },
  { id: 'gen_details', label: 'Detail Level', icon: 'Search', color: 'text-rose-400' },
  { id: 'my_prompts', label: 'My Prompts', icon: 'FileText', color: 'text-zinc-400' },
];

export const GENERAL_BLOCKS: Block[] = [
  // Artistic Style
  { id: 'gs_1', categoryId: 'gen_style', label: 'Realistic Photography', value: 'hyper-realistic photography, 8k resolution' },
  { id: 'gs_2', categoryId: 'gen_style', label: 'Digital Illustration', value: 'digital illustration, vibrant colors' },
  { id: 'gs_3', categoryId: 'gen_style', label: 'Oil Painting', value: 'oil painting style, visible brushstrokes' },
  { id: 'gs_4', categoryId: 'gen_style', label: 'Concept Art', value: 'concept art, highly detailed' },
  { id: 'gs_5', categoryId: 'gen_style', label: 'Cyberpunk', value: 'cyberpunk aesthetic, neon lights, futuristic' },
  { id: 'gs_6', categoryId: 'gen_style', label: 'Steampunk', value: 'steampunk style, brass, gears, victorian' },
  { id: 'gs_7', categoryId: 'gen_style', label: 'Watercolor', value: 'watercolor painting, soft edges, translucent' },
  { id: 'gs_8', categoryId: 'gen_style', label: 'Anime / Manga', value: 'anime style, studio ghibli aesthetic' },
  { id: 'gs_9', categoryId: 'gen_style', label: 'Low Poly / 3D', value: 'low poly 3d render, isometric view' },

  // Main Subject
  { id: 'gsu_1', categoryId: 'gen_subject', label: 'Modern Architecture', value: 'modern architecture building' },
  { id: 'gsu_2', categoryId: 'gen_subject', label: 'Futuristic Vehicle', value: 'futuristic flying vehicle' },
  { id: 'gsu_3', categoryId: 'gen_subject', label: 'Fantastic Creature', value: 'mythical fantasy creature' },
  { id: 'gsu_4', categoryId: 'gen_subject', label: 'Everyday Object', value: 'everyday object, still life' },
  { id: 'gsu_5', categoryId: 'gen_subject', label: 'Food / Drink', value: 'delicious food photography, appetizing' },
  { id: 'gsu_6', categoryId: 'gen_subject', label: 'Ancient Ruins', value: 'ancient ruins, overgrown with vegetation' },
  { id: 'gsu_7', categoryId: 'gen_subject', label: 'Spaceship', value: 'sci-fi spaceship exterior' },

  // Environment / Landscape
  { id: 'ge_1', categoryId: 'gen_environment', label: 'Futuristic City', value: 'futuristic metropolis cityscape' },
  { id: 'ge_2', categoryId: 'gen_environment', label: 'Magical Forest', value: 'enchanted magical forest, glowing plants' },
  { id: 'ge_3', categoryId: 'gen_environment', label: 'Desert', value: 'vast desert landscape, sand dunes' },
  { id: 'ge_4', categoryId: 'gen_environment', label: 'Snowy Mountains', value: 'snow-capped mountain peaks' },
  { id: 'ge_5', categoryId: 'gen_environment', label: 'Underwater Background', value: 'underwater scene, coral reef, sun rays' },
  { id: 'ge_6', categoryId: 'gen_environment', label: 'Outer Space', value: 'outer space, nebula, stars, galaxies' },
  { id: 'ge_7', categoryId: 'gen_environment', label: 'Cozy Interior', value: 'cozy indoor room, warm fireplace' },

  // Lighting
  { id: 'gl_1', categoryId: 'gen_lighting', label: 'Natural Light (Day)', value: 'natural daylight, bright and clear' },
  { id: 'gl_2', categoryId: 'gen_lighting', label: 'Golden Hour', value: 'golden hour lighting, warm sun rays' },
  { id: 'gl_3', categoryId: 'gen_lighting', label: 'Studio Lighting', value: 'professional studio lighting, softbox' },
  { id: 'gl_4', categoryId: 'gen_lighting', label: 'Neon Light', value: 'neon lighting, vibrant pink and blue glows' },
  { id: 'gl_5', categoryId: 'gen_lighting', label: 'Moonlight', value: 'moonlight, cool blue tones, nighttime' },
  { id: 'gl_6', categoryId: 'gen_lighting', label: 'Volumetric Light', value: 'volumetric lighting, god rays' },
  { id: 'gl_7', categoryId: 'gen_lighting', label: 'Low Key Lighting', value: 'low key lighting, dramatic shadows' },

  // Camera / Composition
  { id: 'gc_1', categoryId: 'gen_camera', label: 'Wide Shot', value: 'wide angle shot, expansive view' },
  { id: 'gc_2', categoryId: 'gen_camera', label: 'Close Up', value: 'close up shot, macro photography' },
  { id: 'gc_3', categoryId: 'gen_camera', label: 'Bird\'s Eye View', value: 'bird\'s eye view, looking down from above' },
  { id: 'gc_4', categoryId: 'gen_camera', label: 'Worm\'s Eye View', value: 'worm\'s eye view, looking up from below' },
  { id: 'gc_5', categoryId: 'gen_camera', label: 'Symmetry', value: 'perfect symmetry, centered composition' },
  { id: 'gc_6', categoryId: 'gen_camera', label: 'Rule of Thirds', value: 'rule of thirds composition' },
  { id: 'gc_7', categoryId: 'gen_camera', label: 'Depth of Field', value: 'shallow depth of field, blurred background (bokeh)' },

  // Atmosphere / Mood
  { id: 'gm_1', categoryId: 'gen_mood', label: 'Epic / Majestic', value: 'epic, majestic, awe-inspiring atmosphere' },
  { id: 'gm_2', categoryId: 'gen_mood', label: 'Mysterious / Dark', value: 'mysterious, dark, eerie mood' },
  { id: 'gm_3', categoryId: 'gen_mood', label: 'Quiet / Peaceful', value: 'peaceful, tranquil, serene atmosphere' },
  { id: 'gm_4', categoryId: 'gen_mood', label: 'Chaotic / Dynamic', value: 'chaotic, dynamic, high energy' },
  { id: 'gm_5', categoryId: 'gen_mood', label: 'Melancholic', value: 'melancholic, nostalgic mood' },
  { id: 'gm_6', categoryId: 'gen_mood', label: 'Cheerful / Vibrant', value: 'cheerful, vibrant, uplifting atmosphere' },

  // Color Palette
  { id: 'gco_1', categoryId: 'gen_color', label: 'Pastel Colors', value: 'pastel color palette, soft tones' },
  { id: 'gco_2', categoryId: 'gen_color', label: 'Black and White', value: 'black and white, monochrome' },
  { id: 'gco_3', categoryId: 'gen_color', label: 'Warm Tones', value: 'warm color palette, reds, oranges, yellows' },
  { id: 'gco_4', categoryId: 'gen_color', label: 'Cool Tones', value: 'cool color palette, blues, greens, purples' },
  { id: 'gco_5', categoryId: 'gen_color', label: 'High Contrast', value: 'high contrast colors, vivid' },
  { id: 'gco_6', categoryId: 'gen_color', label: 'Earth Tones', value: 'earth tones, muted natural colors' },

  // Detail Level
  { id: 'gd_1', categoryId: 'gen_details', label: 'Ultra Detailed', value: 'ultra-detailed, intricate details, 8k, highly complex' },
  { id: 'gd_2', categoryId: 'gen_details', label: 'Minimalist', value: 'minimalist, simple, clean lines, uncluttered' },
  { id: 'gd_3', categoryId: 'gen_details', label: 'Abstract', value: 'abstract, non-representational forms' },
  { id: 'gd_4', categoryId: 'gen_details', label: 'Textured', value: 'rich textures, tactile surfaces' },

  // Image Qualities (General)
  { id: 'gq_1', categoryId: 'gen_quality', label: 'Low Quality', value: 'low quality, blurry, pixelated' },
  { id: 'gq_2', categoryId: 'gen_quality', label: 'Medium Quality', value: 'standard quality, clear' },
  { id: 'gq_3', categoryId: 'gen_quality', label: 'High Quality', value: 'high quality, sharp focus, detailed' },
  { id: 'gq_4', categoryId: 'gen_quality', label: '4K', value: '4k resolution, ultra high definition' },
  { id: 'gq_5', categoryId: 'gen_quality', label: '8K', value: '8k resolution, extreme detail' },
  { id: 'gq_6', categoryId: 'gen_quality', label: 'Perfect Plastic Skin', value: 'perfect plastic skin, flawless airbrushed texture, AI aesthetic' },
  { id: 'gq_7', categoryId: 'gen_quality', label: 'Masterpiece', value: 'masterpiece, best quality, award winning' },
  { id: 'gq_8', categoryId: 'gen_quality', label: 'HDR', value: 'high dynamic range, vibrant lighting' },
];

export const ALL_CATEGORIES = [...INFLUENCER_CATEGORIES, ...GENERAL_CATEGORIES];

export const INFLUENCER_BLOCKS: Block[] = [
  // Visual Result
  { id: 'res_1', categoryId: 'result', label: 'Casual spontaneous', value: 'casual spontaneous' },
  { id: 'res_2', categoryId: 'result', label: 'Natural selfie', value: 'natural selfie' },
  { id: 'res_3', categoryId: 'result', label: 'Magazine editorial', value: 'magazine editorial' },
  { id: 'res_4', categoryId: 'result', label: 'Professional studio', value: 'professional studio' },
  { id: 'res_5', categoryId: 'result', label: 'Cinematic', value: 'cinematic' },
  { id: 'res_6', categoryId: 'result', label: 'Aesthetic', value: 'aesthetic' },
  { id: 'res_7', categoryId: 'result', label: 'Film grain', value: 'film grain' },
  { id: 'res_8', categoryId: 'result', label: 'Product commercial', value: 'product commercial' },
  { id: 'res_9', categoryId: 'result', label: 'Intimate portrait', value: 'intimate portrait' },
  { id: 'res_10', categoryId: 'result', label: 'Urban lifestyle', value: 'urban lifestyle' },
  { id: 'res_11', categoryId: 'result', label: 'Vintage polaroid', value: 'vintage polaroid photo' },
  { id: 'res_12', categoryId: 'result', label: 'Disposable camera', value: 'disposable camera aesthetic' },
  { id: 'res_13', categoryId: 'result', label: 'Street photography', value: 'street photography' },
  { id: 'res_14', categoryId: 'result', label: 'Haute couture', value: 'haute couture fashion photography' },
  { id: 'res_15', categoryId: 'result', label: 'Cyberpunk', value: 'cyberpunk aesthetic' },
  { id: 'res_16', categoryId: 'result', label: 'Dark fantasy', value: 'dark fantasy aesthetic' },

  // Main Focus
  { id: 'foc_1', categoryId: 'focus', label: 'Selfie', value: 'selfie focus, subject is the main subject' },
  { id: 'foc_2', categoryId: 'focus', label: 'Face focus', value: 'face focus, close up on the face' },
  { id: 'foc_3', categoryId: 'focus', label: 'Feet focus', value: 'feet focus, feet are the main subject' },
  { id: 'foc_4', categoryId: 'focus', label: 'Neck focus', value: 'neck focus' },
  { id: 'foc_5', categoryId: 'focus', label: 'Environment focus', value: 'environment focus, subject is small in the frame' },
  { id: 'foc_6', categoryId: 'focus', label: 'Gesture focus', value: 'gesture focus, focusing on a specific hand or facial gesture' },
  { id: 'foc_7', categoryId: 'focus', label: 'Background interaction', value: 'focus on interaction with the background' },
  { id: 'foc_8', categoryId: 'focus', label: 'Lips focus', value: 'close up focus on lips' },
  { id: 'foc_9', categoryId: 'focus', label: 'Eyes focus', value: 'close up focus on eyes' },
  { id: 'foc_10', categoryId: 'focus', label: 'Hands focus', value: 'close up focus on hands' },
  { id: 'foc_11', categoryId: 'focus', label: 'Silhouette focus', value: 'focus on body silhouette' },

  // Scene Type
  { id: 'sce_1', categoryId: 'scene', label: 'In bedroom', value: 'in a cozy bedroom' },
  { id: 'sce_2', categoryId: 'scene', label: 'In bed', value: 'in bed' },
  { id: 'sce_3', categoryId: 'scene', label: 'In kitchen', value: 'in a kitchen' },
  { id: 'sce_4', categoryId: 'scene', label: 'On the street', value: 'on the street' },
  { id: 'sce_5', categoryId: 'scene', label: 'At a concert', value: 'at a concert' },
  { id: 'sce_6', categoryId: 'scene', label: 'At school', value: 'at school' },
  { id: 'sce_7', categoryId: 'scene', label: 'Solid background', value: 'solid background' },
  { id: 'sce_8', categoryId: 'scene', label: 'Contrast background', value: 'high contrast background' },
  { id: 'sce_9', categoryId: 'scene', label: 'Warm interior', value: 'warm interior' },
  { id: 'sce_10', categoryId: 'scene', label: 'Everyday exterior', value: 'everyday exterior' },
  { id: 'sce_11', categoryId: 'scene', label: 'At the beach', value: 'at the beach' },
  { id: 'sce_12', categoryId: 'scene', label: 'In the forest', value: 'in a dense forest' },
  { id: 'sce_13', categoryId: 'scene', label: 'In a cafe', value: 'in a cozy coffee shop' },
  { id: 'sce_14', categoryId: 'scene', label: 'At the gym', value: 'at the gym' },
  { id: 'sce_15', categoryId: 'scene', label: 'In a bar', value: 'in a dimly lit bar' },
  { id: 'sce_16', categoryId: 'scene', label: 'On public transport', value: 'on public transport, subway or bus' },
  { id: 'sce_17', categoryId: 'scene', label: 'In a botanical garden', value: 'in a lush botanical garden' },
  { id: 'sce_18', categoryId: 'scene', label: 'In an old library', value: 'in an old library with wooden shelves' },
  { id: 'sce_19', categoryId: 'scene', label: 'On a rooftop', value: 'on a city rooftop at sunset' },
  { id: 'sce_20', categoryId: 'scene', label: 'In an art studio', value: 'in a messy art studio with canvases' },
  { id: 'sce_21', categoryId: 'scene', label: 'In a shopping mall', value: 'in a modern shopping mall' },
  { id: 'sce_22', categoryId: 'scene', label: 'At an amusement park', value: 'at an amusement park with lights' },
  { id: 'sce_23', categoryId: 'scene', label: 'On a balcony', value: 'on a balcony overlooking the city' },
  { id: 'sce_24', categoryId: 'scene', label: 'In an elevator', value: 'inside a modern elevator' },

  // Environment
  { id: 'env_1', categoryId: 'environment', label: 'Dawn', value: 'early morning, dawn' },
  { id: 'env_2', categoryId: 'environment', label: 'Day', value: 'daytime, bright daylight' },
  { id: 'env_3', categoryId: 'environment', label: 'Afternoon', value: 'late afternoon' },
  { id: 'env_4', categoryId: 'environment', label: 'Night', value: 'nighttime, dark' },
  { id: 'env_5', categoryId: 'environment', label: 'Indoor variations', value: 'indoor ambient variations' },
  { id: 'env_6', categoryId: 'environment', label: 'Rainy', value: 'rainy weather, wet surfaces' },
  { id: 'env_7', categoryId: 'environment', label: 'Cloudy', value: 'overcast, cloudy sky' },
  { id: 'env_8', categoryId: 'environment', label: 'Snowy', value: 'snowy environment, winter' },
  { id: 'env_9', categoryId: 'environment', label: 'Dense fog', value: 'dense fog, mysterious atmosphere' },
  { id: 'env_10', categoryId: 'environment', label: 'Thunderstorm', value: 'thunderstorm, lightning in the distance' },
  { id: 'env_11', categoryId: 'environment', label: 'Purple sunset', value: 'purple and orange sunset sky' },
  { id: 'env_12', categoryId: 'environment', label: 'Morning mist light', value: 'soft morning mist and sunbeams' },
  { id: 'env_13', categoryId: 'environment', label: 'Sweltering heat', value: 'heat haze, shimmering air' },
  { id: 'env_14', categoryId: 'environment', label: 'Strong wind', value: 'windy atmosphere, dust motes' },

  // Action / Situation
  { id: 'act_1', categoryId: 'action', label: 'Walking', value: 'walking' },
  { id: 'act_2', categoryId: 'action', label: 'Posing alone', value: 'posing alone' },
  { id: 'act_3', categoryId: 'action', label: 'Eating', value: 'eating' },
  { id: 'act_4', categoryId: 'action', label: 'Hanging out with friends', value: 'hanging out with friends' },
  { id: 'act_5', categoryId: 'action', label: 'Taking selfie', value: 'taking a selfie' },
  { id: 'act_6', categoryId: 'action', label: 'Showing product', value: 'showing a product' },
  { id: 'act_7', categoryId: 'action', label: 'Sitting resting', value: 'sitting and resting' },
  { id: 'act_8', categoryId: 'action', label: 'Interacting with object', value: 'interacting with an object' },
  { id: 'act_9', categoryId: 'action', label: 'Candid moment', value: 'candid stolen moment' },
  { id: 'act_10', categoryId: 'action', label: 'Dancing', value: 'dancing energetically' },
  { id: 'act_11', categoryId: 'action', label: 'Reading a book', value: 'reading a book' },
  { id: 'act_12', categoryId: 'action', label: 'Drinking coffee', value: 'drinking coffee' },
  { id: 'act_13', categoryId: 'action', label: 'Looking at phone', value: 'looking at smartphone' },
  { id: 'act_14', categoryId: 'action', label: 'Adjusting hair', value: 'adjusting hair' },
  { id: 'act_15', categoryId: 'action', label: 'Working out', value: 'working out, intense exercise' },
  { id: 'act_16', categoryId: 'action', label: 'Listening to music', value: 'listening to music with headphones' },
  { id: 'act_17', categoryId: 'action', label: 'Painting/Drawing', value: 'painting on a canvas' },
  { id: 'act_18', categoryId: 'action', label: 'Cooking', value: 'cooking a meal' },
  { id: 'act_19', categoryId: 'action', label: 'Talking on phone', value: 'talking on the phone' },
  { id: 'act_20', categoryId: 'action', label: 'Meditating', value: 'meditating peacefully' },
  { id: 'act_21', categoryId: 'action', label: 'Taking photos', value: 'taking photos with a professional camera' },
  { id: 'act_22', categoryId: 'action', label: 'Waiting for bus', value: 'waiting at a bus stop' },
  { id: 'act_23', categoryId: 'action', label: 'Applying makeup', value: 'applying makeup in front of a mirror' },
  { id: 'act_24', categoryId: 'action', label: 'Whispering', value: 'whispering into someone\'s ear' },

  // Movement
  { id: 'mov_1', categoryId: 'movement', label: 'Completely still', value: 'completely still, posing' },
  { id: 'mov_2', categoryId: 'movement', label: 'Walking (motion)', value: 'walking motion' },
  { id: 'mov_3', categoryId: 'movement', label: 'Slight motion blur', value: 'slight motion blur' },
  { id: 'mov_4', categoryId: 'movement', label: 'Heavy motion (running)', value: 'heavy motion blur, running or escaping' },
  { id: 'mov_5', categoryId: 'movement', label: 'Rotating angle', value: 'rotating camera angle, dynamic movement' },
  { id: 'mov_6', categoryId: 'movement', label: 'Zoom in/out', value: 'zoom burst effect' },
  { id: 'mov_7', categoryId: 'movement', label: 'Light trails (night)', value: 'light trails, night motion' },
  { id: 'mov_8', categoryId: 'movement', label: 'Hair in the wind', value: 'hair blowing in the wind' },
  { id: 'mov_9', categoryId: 'movement', label: 'Clothes fluttering', value: 'clothes fluttering in the wind' },
  { id: 'mov_10', categoryId: 'movement', label: 'Jumping', value: 'jumping in the air, frozen motion' },
  { id: 'mov_11', categoryId: 'movement', label: 'Free fall', value: 'falling through the air' },
  { id: 'mov_12', categoryId: 'movement', label: 'Quick spin', value: 'spinning around quickly' },

  // Gesticulation
  { id: 'ges_1', categoryId: 'gesticulation', label: 'Matching expression', value: 'expression naturally adapted to the action' },
  { id: 'ges_2', categoryId: 'gesticulation', label: 'Believable hands', value: 'hands interacting naturally' },
  { id: 'ges_3', categoryId: 'gesticulation', label: 'Natural posture', value: 'natural posture' },
  { id: 'ges_4', categoryId: 'gesticulation', label: 'Looking at camera', value: 'looking directly at the camera' },
  { id: 'ges_5', categoryId: 'gesticulation', label: 'Looking away', value: 'looking away thoughtfully' },
  { id: 'ges_6', categoryId: 'gesticulation', label: 'Wide smile', value: 'wide happy smile' },
  { id: 'ges_7', categoryId: 'gesticulation', label: 'Serious expression', value: 'serious, stoic expression' },
  { id: 'ges_8', categoryId: 'gesticulation', label: 'Wink', value: 'winking one eye' },
  { id: 'ges_9', categoryId: 'gesticulation', label: 'Biting lip', value: 'biting lip gently' },
  { id: 'ges_10', categoryId: 'gesticulation', label: 'Surprise', value: 'surprised expression' },
  { id: 'ges_11', categoryId: 'gesticulation', label: 'Subtle anger', value: 'subtle angry expression, furrowed brow' },
  { id: 'ges_12', categoryId: 'gesticulation', label: 'Melancholic sadness', value: 'melancholic, sad expression' },
  { id: 'ges_13', categoryId: 'gesticulation', label: 'Uncontrollable laughter', value: 'laughing uncontrollably' },
  { id: 'ges_14', categoryId: 'gesticulation', label: 'Boredom', value: 'bored, uninterested expression' },
  { id: 'ges_15', categoryId: 'gesticulation', label: 'Seduction', value: 'seductive, alluring gaze' },
  { id: 'ges_16', categoryId: 'gesticulation', label: 'Concentration', value: 'deep concentration, focused eyes' },

  // Exposed Parts
  { id: 'exp_1', categoryId: 'exposed_body', label: 'Visible arms', value: 'bare arms visible, realistic skin texture' },
  { id: 'exp_2', categoryId: 'exposed_body', label: 'Abdomen (crop top)', value: 'bare midriff, visible abdomen, crop top style' },
  { id: 'exp_3', categoryId: 'exposed_body', label: 'Visible legs', value: 'bare legs visible, realistic skin texture' },
  { id: 'exp_4', categoryId: 'exposed_body', label: 'Visible thighs', value: 'bare thighs visible' },
  { id: 'exp_5', categoryId: 'exposed_body', label: 'Visible feet', value: 'bare feet visible, detailed' },
  { id: 'exp_6', categoryId: 'exposed_body', label: 'Visible hands', value: 'hands visible, realistic skin texture' },
  { id: 'exp_7', categoryId: 'exposed_body', label: 'Visible back', value: 'bare back visible, realistic skin texture' },
  { id: 'exp_8', categoryId: 'exposed_body', label: 'Visible knees', value: 'bare knees visible' },
  { id: 'exp_9', categoryId: 'exposed_body', label: 'Visible shoulders', value: 'bare shoulders visible' },
  { id: 'exp_10', categoryId: 'exposed_body', label: 'Visible elbows', value: 'bare elbows visible' },
  { id: 'exp_11', categoryId: 'exposed_body', label: 'Visible neck', value: 'bare neck visible' },
  { id: 'exp_12', categoryId: 'exposed_body', label: 'Topless', value: 'topless, bare upper body, realistic skin texture', isNsfw: true },
  { id: 'exp_13', categoryId: 'exposed_body', label: 'Bottomless', value: 'bottomless, bare lower body, realistic skin texture', isNsfw: true },
  { id: 'exp_14', categoryId: 'exposed_body', label: 'Full nudity', value: 'completely nude, full body realistic skin texture', isNsfw: true },
  { id: 'exp_15', categoryId: 'exposed_body', label: 'Visible nipples', value: 'visible nipples', isNsfw: true },
  { id: 'exp_16', categoryId: 'exposed_body', label: 'Visible vagina', value: 'visible vagina', isNsfw: true },
  { id: 'exp_17', categoryId: 'exposed_body', label: 'Visible penis', value: 'visible penis', isNsfw: true },
  { id: 'exp_18', categoryId: 'exposed_body', label: 'Exposed buttocks', value: 'bare buttocks exposed', isNsfw: true },

  // Camera / Angle
  { id: 'cam_1', categoryId: 'camera', label: 'Close up', value: 'close up shot' },
  { id: 'cam_2', categoryId: 'camera', label: 'Medium shot', value: 'medium shot' },
  { id: 'cam_3', categoryId: 'camera', label: 'Full body', value: 'full body shot' },
  { id: 'cam_4', categoryId: 'camera', label: 'High angle', value: 'high angle' },
  { id: 'cam_5', categoryId: 'camera', label: 'Low angle', value: 'low angle' },
  { id: 'cam_6', categoryId: 'camera', label: 'Selfie angle', value: 'selfie angle' },
  { id: 'cam_7', categoryId: 'camera', label: 'Side angle', value: 'side angle' },
  { id: 'cam_8', categoryId: 'camera', label: 'Centered composition', value: 'centered composition' },
  { id: 'cam_9', categoryId: 'camera', label: 'Paparazzi style', value: 'paparazzi style' },
  { id: 'cam_10', categoryId: 'camera', label: 'Bird\'s eye view', value: 'bird\'s eye view' },
  { id: 'cam_11', categoryId: 'camera', label: 'Worm\'s eye view', value: 'worm\'s eye view' },
  { id: 'cam_12', categoryId: 'camera', label: 'Dutch angle', value: 'dutch angle, tilted camera' },
  { id: 'cam_13', categoryId: 'camera', label: 'Detail shot', value: 'extreme close up, macro shot' },
  { id: 'cam_14', categoryId: 'camera', label: 'From behind', value: 'shot from behind' },
  { id: 'cam_15', categoryId: 'camera', label: 'Over the shoulder', value: 'over-the-shoulder shot' },
  { id: 'cam_16', categoryId: 'camera', label: 'Extreme wide shot', value: 'extreme wide shot' },

  // Lenses / Parameters
  { id: 'len_1', categoryId: 'lens', label: '24mm', value: 'shot on 24mm lens' },
  { id: 'len_2', categoryId: 'lens', label: '35mm', value: 'shot on 35mm lens' },
  { id: 'len_3', categoryId: 'lens', label: '50mm', value: 'shot on 50mm lens' },
  { id: 'len_4', categoryId: 'lens', label: '85mm', value: 'shot on 85mm lens' },
  { id: 'len_5', categoryId: 'lens', label: 'Telephoto', value: 'telephoto lens' },
  { id: 'len_6', categoryId: 'lens', label: 'Wide angle', value: 'wide angle lens' },
  { id: 'len_7', categoryId: 'lens', label: 'f/1.8', value: 'f/1.8 aperture' },
  { id: 'len_8', categoryId: 'lens', label: 'Blurred background', value: 'shallow depth of field, blurred background' },
  { id: 'len_9', categoryId: 'lens', label: 'Studio sharpness', value: 'studio sharpness' },
  { id: 'len_10', categoryId: 'lens', label: 'Fisheye', value: 'fisheye lens effect' },
  { id: 'len_11', categoryId: 'lens', label: 'Anamorphic lens', value: 'anamorphic lens flare' },
  { id: 'len_12', categoryId: 'lens', label: 'iPhone camera', value: 'shot on iPhone camera, natural smartphone photography' },
  { id: 'len_13', categoryId: 'lens', label: 'Macro lens', value: 'macro lens, extreme detail' },
  { id: 'len_14', categoryId: 'lens', label: 'Vintage filter', value: 'vintage lens filter, soft edges' },

  // Lighting
  { id: 'lig_1', categoryId: 'lighting', label: 'Natural light', value: 'natural lighting' },
  { id: 'lig_2', categoryId: 'lighting', label: 'Window light', value: 'window light' },
  { id: 'lig_3', categoryId: 'lighting', label: 'Golden hour', value: 'golden hour lighting' },
  { id: 'lig_4', categoryId: 'lighting', label: 'Artificial light', value: 'artificial lighting' },
  { id: 'lig_5', categoryId: 'lighting', label: 'Hard light', value: 'hard light' },
  { id: 'lig_6', categoryId: 'lighting', label: 'Soft light', value: 'soft diffused light' },
  { id: 'lig_7', categoryId: 'lighting', label: 'Color neon', value: 'colorful neon lighting' },
  { id: 'lig_8', categoryId: 'lighting', label: 'Backlighting', value: 'backlighting' },
  { id: 'lig_9', categoryId: 'lighting', label: 'Editorial lighting', value: 'editorial lighting setup' },
  { id: 'lig_10', categoryId: 'lighting', label: 'Moonlight', value: 'moonlight illumination' },
  { id: 'lig_11', categoryId: 'lighting', label: 'Candlelight', value: 'candlelight, warm glow' },
  { id: 'lig_12', categoryId: 'lighting', label: 'Direct flash', value: 'direct flash photography' },
  { id: 'lig_13', categoryId: 'lighting', label: 'Dramatic lighting', value: 'dramatic chiaroscuro lighting' },
  { id: 'lig_14', categoryId: 'lighting', label: 'Disco light', value: 'disco lights, strobes, colorful beams' },
  { id: 'lig_15', categoryId: 'lighting', label: 'Sunset light', value: 'warm sunset light' },
  { id: 'lig_16', categoryId: 'lighting', label: 'Volumetric light', value: 'volumetric lighting, god rays' },

  // Realism
  { id: 'rea_1', categoryId: 'realism', label: 'Visible pores', value: 'visible skin pores' },
  { id: 'rea_2', categoryId: 'realism', label: 'Natural texture', value: 'natural skin texture' },
  { id: 'rea_3', categoryId: 'realism', label: 'Micro-imperfections', value: 'facial micro-details and imperfections' },
  { id: 'rea_4', categoryId: 'realism', label: 'Subtle wrinkles', value: 'subtle wrinkles' },
  { id: 'rea_5', categoryId: 'realism', label: 'Real hair', value: 'natural hair strands' },
  { id: 'rea_6', categoryId: 'realism', label: 'Fabric folds', value: 'believable fabric folds' },
  { id: 'rea_7', categoryId: 'realism', label: 'Natural shadows', value: 'true-to-life ambient shadows' },
  { id: 'rea_8', categoryId: 'realism', label: 'Realistic skin (body)', value: 'realistic skin texture on the entire body, not just the face' },
  { id: 'rea_9', categoryId: 'realism', label: 'Freckles and moles', value: 'natural freckles and moles' },
  { id: 'rea_10', categoryId: 'realism', label: 'Light sweat', value: 'light sweat or moisture on skin' },
  { id: 'rea_11', categoryId: 'realism', label: 'Subtle body hair', value: 'subtle natural body hair' },
  { id: 'rea_12', categoryId: 'realism', label: 'Subtle scars', value: 'subtle realistic scars' },
  { id: 'rea_13', categoryId: 'realism', label: 'Visible veins', value: 'subtle visible veins under skin' },

  // Outfit / Styling
  { id: 'out_1', categoryId: 'outfit', label: 'Dark outfit', value: 'dark outfit' },
  { id: 'out_2', categoryId: 'outfit', label: 'Streetwear', value: 'streetwear' },
  { id: 'out_3', categoryId: 'outfit', label: 'Casual', value: 'casual wear' },
  { id: 'out_4', categoryId: 'outfit', label: 'Elegant', value: 'elegant attire' },
  { id: 'out_5', categoryId: 'outfit', label: 'Minimalist', value: 'minimalist clothing' },
  { id: 'out_6', categoryId: 'outfit', label: 'Black crop top', value: 'black crop top' },
  { id: 'out_7', categoryId: 'outfit', label: 'Dress', value: 'dress' },
  { id: 'out_8', categoryId: 'outfit', label: 'Tattoos', value: 'tattoos' },
  { id: 'out_9', categoryId: 'outfit', label: 'Dark makeup', value: 'dark eye makeup' },
  { id: 'out_10', categoryId: 'outfit', label: 'Sportswear', value: 'sportswear, athletic clothing' },
  { id: 'out_11', categoryId: 'outfit', label: 'Swimsuit', value: 'swimsuit, bikini' },
  { id: 'out_12', categoryId: 'outfit', label: 'Lingerie', value: 'lingerie', isNsfw: true },
  { id: 'out_13', categoryId: 'outfit', label: 'Winter clothing', value: 'winter clothing, heavy coat' },
  { id: 'out_14', categoryId: 'outfit', label: 'Sunglasses', value: 'wearing sunglasses' },
  { id: 'out_15', categoryId: 'outfit', label: 'Transparent clothing', value: 'see-through clothing, sheer fabric', isNsfw: true },
  { id: 'out_16', categoryId: 'outfit', label: 'Gothic style', value: 'gothic fashion style' },
  { id: 'out_17', categoryId: 'outfit', label: 'Leather clothing', value: 'leather clothing' },
  { id: 'out_18', categoryId: 'outfit', label: 'School uniform', value: 'school uniform' },
  { id: 'out_19', categoryId: 'outfit', label: 'Pajamas', value: 'pajamas, sleepwear' },
  { id: 'out_20', categoryId: 'outfit', label: 'Silk clothing', value: 'silk clothing, smooth texture' },

  // Makeup
  { id: 'mak_1', categoryId: 'makeup', label: 'Natural / No-makeup', value: 'no-makeup makeup look, natural skin' },
  { id: 'mak_2', categoryId: 'makeup', label: 'E-girl', value: 'e-girl makeup, heavy blush, winged eyeliner' },
  { id: 'mak_3', categoryId: 'makeup', label: 'Gloss only', value: 'clear lip gloss only, bare face' },
  { id: 'mak_4', categoryId: 'makeup', label: 'Graphic eyeliner', value: 'graphic eyeliner, sharp wings' },
  { id: 'mak_5', categoryId: 'makeup', label: 'Smokey eye', value: 'dark smokey eye makeup' },
  { id: 'mak_6', categoryId: 'makeup', label: 'Red lips', value: 'classic red lipstick' },
  { id: 'mak_7', categoryId: 'makeup', label: 'Drag makeup', value: 'drag queen makeup, exaggerated features, heavy contour' },
  { id: 'mak_8', categoryId: 'makeup', label: 'Faux freckles', value: 'faux freckles' },
  { id: 'mak_9', categoryId: 'makeup', label: 'Neon eyeshadow', value: 'neon eyeshadow' },
  { id: 'mak_10', categoryId: 'makeup', label: 'Soft glam', value: 'soft glam makeup, glowing skin' },
  { id: 'mak_11', categoryId: 'makeup', label: 'Gothic', value: 'goth makeup, black lipstick, pale skin' },
  { id: 'mak_12', categoryId: 'makeup', label: 'Euphoria style', value: 'euphoria makeup, rhinestones, glitter' },
  { id: 'mak_13', categoryId: 'makeup', label: 'Fantasy makeup', value: 'fantasy makeup, artistic patterns' },

  // Palette / Color
  { id: 'col_1', categoryId: 'color', label: 'Neutrals', value: 'neutral color palette' },
  { id: 'col_2', categoryId: 'color', label: 'Darks', value: 'dark color palette' },
  { id: 'col_3', categoryId: 'color', label: 'Warms', value: 'warm color palette' },
  { id: 'col_4', categoryId: 'color', label: 'Colds', value: 'cold color palette' },
  { id: 'col_5', categoryId: 'color', label: 'Monochromatic', value: 'monochromatic' },
  { id: 'col_6', categoryId: 'color', label: 'High contrast', value: 'high contrast colors' },
  { id: 'col_7', categoryId: 'color', label: 'Red accents', value: 'red accents' },
  { id: 'col_8', categoryId: 'color', label: 'Total black', value: 'all black palette' },
  { id: 'col_9', categoryId: 'color', label: 'Pastel tones', value: 'pastel color palette' },
  { id: 'col_10', categoryId: 'color', label: 'Black and white', value: 'black and white photography' },
  { id: 'col_11', categoryId: 'color', label: 'High saturation', value: 'vibrant, highly saturated colors' },
  { id: 'col_12', categoryId: 'color', label: 'Earth tones', value: 'earth tones, brown and green palette' },
  { id: 'col_13', categoryId: 'color', label: 'Gold and black', value: 'gold and black color scheme' },
  { id: 'col_14', categoryId: 'color', label: 'Electric blue', value: 'electric blue accents' },

  // Background and Props
  { id: 'pro_1', categoryId: 'props', label: 'Circular rug', value: 'circular rug on the floor' },
  { id: 'pro_2', categoryId: 'props', label: 'Mirror', value: 'mirror' },
  { id: 'pro_3', categoryId: 'props', label: 'Posters', value: 'posters on the wall' },
  { id: 'pro_4', categoryId: 'props', label: 'Messy bed', value: 'aesthetic messy bed' },
  { id: 'pro_5', categoryId: 'props', label: 'Warm lamp', value: 'warm lamp' },
  { id: 'pro_6', categoryId: 'props', label: 'Smartphone', value: 'smartphone' },
  { id: 'pro_7', categoryId: 'props', label: 'Makeup', value: 'makeup items' },
  { id: 'pro_8', categoryId: 'props', label: 'Indoor plants', value: 'indoor plants, monstera' },
  { id: 'pro_9', categoryId: 'props', label: 'Coffee mug', value: 'coffee mug' },
  { id: 'pro_10', categoryId: 'props', label: 'Stacked books', value: 'stack of books' },
  { id: 'pro_11', categoryId: 'props', label: 'Musical instrument', value: 'musical instrument, guitar' },
  { id: 'pro_12', categoryId: 'props', label: 'Sports car', value: 'sports car in the background' },
  { id: 'pro_13', categoryId: 'props', label: 'Open laptop', value: 'open laptop on a desk' },
  { id: 'pro_14', categoryId: 'props', label: 'Large headphones', value: 'large over-ear headphones' },
  { id: 'pro_15', categoryId: 'props', label: 'Vintage camera', value: 'vintage film camera' },
  { id: 'pro_16', categoryId: 'props', label: 'Pet (dog/cat)', value: 'a cute pet nearby' },
  { id: 'pro_17', categoryId: 'props', label: 'Fast food', value: 'fast food, pizza or burger' },
  { id: 'pro_18', categoryId: 'props', label: 'Energy drink', value: 'energy drink can' },
  { id: 'pro_19', categoryId: 'props', label: 'Backpack', value: 'backpack' },
  { id: 'pro_20', categoryId: 'props', label: 'Skateboard', value: 'skateboard leaning against a wall' },


  // Intention
  { id: 'int_1', categoryId: 'intention', label: 'For social media', value: 'social media feel' },
  { id: 'int_2', categoryId: 'intention', label: 'For brand', value: 'brand photography' },
  { id: 'int_3', categoryId: 'intention', label: 'Casual campaign', value: 'casual campaign' },
  { id: 'int_4', categoryId: 'intention', label: 'Aspirational image', value: 'aspirational image' },
  { id: 'int_5', categoryId: 'intention', label: 'Lookbook', value: 'fashion lookbook' },
  { id: 'int_6', categoryId: 'intention', label: 'Documentary photography', value: 'documentary photography style' },
  { id: 'int_7', categoryId: 'intention', label: 'Conceptual art', value: 'conceptual art photography' },
  { id: 'int_8', categoryId: 'intention', label: 'Movie poster', value: 'movie poster aesthetic' },

  // Body Details
  { id: 'bod_1', categoryId: 'body_details', label: 'Height: Tall', value: 'tall height, long limbs' },
  { id: 'bod_2', categoryId: 'body_details', label: 'Height: Average', value: 'average height' },
  { id: 'bod_3', categoryId: 'body_details', label: 'Height: Short', value: 'short height, petite' },
  { id: 'bod_4', categoryId: 'body_details', label: 'Long legs', value: 'long slender legs' },
  { id: 'bod_5', categoryId: 'body_details', label: 'Bust size', value: 'specific bust size' },
  { id: 'bod_6', categoryId: 'body_details', label: 'Porcelain skin', value: 'pale porcelain skin, smooth and flawless' },
  { id: 'bod_7', categoryId: 'body_details', label: 'Moisturized skin', value: 'moisturized glowing skin, dewy texture' },
  { id: 'bod_8', categoryId: 'body_details', label: 'Dry skin', value: 'dry skin texture, matte finish' },
  { id: 'bod_9', categoryId: 'body_details', label: 'Natural/Healthy skin', value: 'natural healthy skin texture' },
  { id: 'bod_10', categoryId: 'body_details', label: 'Natural redness (Feet)', value: 'natural pinkish redness on feet and soles' },
  { id: 'bod_11', categoryId: 'body_details', label: 'Natural redness (Knees)', value: 'natural pinkish redness on knees' },
  { id: 'bod_12', categoryId: 'body_details', label: 'Natural redness (Cheeks)', value: 'natural rosy cheeks' },
  { id: 'bod_13', categoryId: 'body_details', label: 'Birthmark detail', value: 'unique birthmark or skin detail' },
  { id: 'bod_14', categoryId: 'body_details', label: 'Tanned skin', value: 'sun-kissed tanned skin' },
  { id: 'bod_15', categoryId: 'body_details', label: 'Freckled skin (body)', value: 'freckles scattered across the body' },
  { id: 'bod_16', categoryId: 'body_details', label: 'Athletic build', value: 'athletic toned body build' },
  { id: 'bod_17', categoryId: 'body_details', label: 'Slender build', value: 'slender slim body build' },
  { id: 'bod_18', categoryId: 'body_details', label: 'Curvy build', value: 'curvy hourglass body shape' },
  { id: 'bod_19', categoryId: 'body_details', label: 'Pale skin', value: 'fair pale skin tone' },
  { id: 'bod_20', categoryId: 'body_details', label: 'Brown skin', value: 'brown skin tone' },
  { id: 'bod_21', categoryId: 'body_details', label: 'Dark skin', value: 'dark skin tone' },
  { id: 'bod_22', categoryId: 'body_details', label: 'Subtle veins', value: 'subtle visible blue veins under fair skin' },
  { id: 'bod_23', categoryId: 'body_details', label: 'Body: Hourglass', value: 'hourglass body shape' },
  { id: 'bod_24', categoryId: 'body_details', label: 'Body: Pear', value: 'pear-shaped body' },
  { id: 'bod_25', categoryId: 'body_details', label: 'Body: Rectangular', value: 'rectangular body shape' },
  { id: 'bod_26', categoryId: 'body_details', label: 'Legs: Muscular', value: 'muscular toned legs' },
  { id: 'bod_27', categoryId: 'body_details', label: 'Legs: Slender', value: 'thin slender legs' },
  { id: 'bod_28', categoryId: 'body_details', label: 'Feet: High arches', value: 'high arched feet' },
  { id: 'bod_29', categoryId: 'body_details', label: 'Feet: Painted nails', value: 'painted toenails, pedicure' },
  { id: 'bod_30', categoryId: 'body_details', label: 'Feet: Pinkish soles', value: 'pinkish soles of feet' },
  { id: 'bod_31', categoryId: 'body_details', label: 'Detail: Prominent collarbones', value: 'prominent collarbones' },
  { id: 'bod_32', categoryId: 'body_details', label: 'Detail: Defined back', value: 'defined back muscles' },
  { id: 'bod_33', categoryId: 'body_details', label: 'Detail: Delicate hands', value: 'delicate slender hands' },
  { id: 'bod_34', categoryId: 'body_details', label: 'Detail: Long neck', value: 'long elegant neck' },
  { id: 'bod_35', categoryId: 'body_details', label: 'Skin: Subtle body hair', value: 'subtle natural body hair' },
  { id: 'bod_36', categoryId: 'body_details', label: 'Skin: Stretch marks', value: 'realistic stretch marks' },
  { id: 'bod_37', categoryId: 'body_details', label: 'Skin: Cellulite', value: 'realistic cellulite texture' },

  // Image Quality (Influencer)
  { id: 'q_1', categoryId: 'quality', label: 'Low Quality', value: 'low quality, blurry' },
  { id: 'q_2', categoryId: 'quality', label: 'Medium Quality', value: 'standard quality' },
  { id: 'q_3', categoryId: 'quality', label: 'High Quality', value: 'high quality, sharp' },
  { id: 'q_4', categoryId: 'quality', label: '4K', value: '4k' },
  { id: 'q_5', categoryId: 'quality', label: '8K', value: '8k' },
  { id: 'q_6', categoryId: 'quality', label: 'Perfect Plastic Skin', value: 'perfect plastic skin, flawless AI texture' },
  { id: 'q_7', categoryId: 'quality', label: 'Realistic HD', value: 'realistic HD photography' },
  { id: 'q_8', categoryId: 'quality', label: 'Raw Photo', value: 'unprocessed raw photo, natural' },

  // Restrictions / Negatives
  { id: 'neg_1', categoryId: 'negative', label: 'Avoid deformed hands', value: 'avoid deformed hands' },
  { id: 'neg_2', categoryId: 'negative', label: 'Avoid overprocessed look', value: 'avoid overprocessed look' },
  { id: 'neg_3', categoryId: 'negative', label: 'Avoid plastic skin', value: 'avoid plastic skin' },
  { id: 'neg_4', categoryId: 'negative', label: 'Avoid impossible poses', value: 'avoid impossible poses' },
  { id: 'neg_5', categoryId: 'negative', label: 'Avoid empty expressions', value: 'avoid empty expressions' },
  { id: 'neg_6', categoryId: 'negative', label: 'Avoid text', value: 'avoid text, watermarks, signatures' },
  { id: 'neg_7', categoryId: 'negative', label: 'Avoid facial asymmetry', value: 'avoid facial asymmetry' },
  { id: 'neg_8', categoryId: 'negative', label: 'Avoid censorship', value: 'avoid censorship bars or blur', isNsfw: true },
];

import { Preset } from './types';

export const PRESETS: Preset[] = [
  {
    id: 'preset_1',
    label: 'Influencer Social Media',
    description: 'Natural selfie, skin texture, casual lighting.',
    icon: 'Instagram',
    blockIds: ['res_2', 'rea_1', 'rea_2', 'lig_1', 'cam_6', 'sce_1', 'act_5']
  },
  {
    id: 'preset_2',
    label: 'Professional Studio',
    description: 'Hard lighting, high fashion, solid background.',
    icon: 'Camera',
    blockIds: ['res_4', 'lig_5', 'len_4', 'cam_3', 'sce_7', 'out_4']
  },
  {
    id: 'preset_3',
    label: 'Cinematic Night',
    description: 'Neon light, rain, cyberpunk, 35mm.',
    icon: 'Film',
    blockIds: ['res_5', 'env_4', 'env_6', 'lig_7', 'len_2', 'res_15']
  },
  {
    id: 'preset_4',
    label: 'Vintage Polaroid',
    description: 'Film grain, direct flash, spontaneous.',
    icon: 'Image',
    blockIds: ['res_11', 'res_7', 'lig_12', 'act_9', 'col_3']
  },
  {
    id: 'preset_5',
    label: 'Intimate Boudoir (NSFW)',
    description: 'Soft light, lingerie, realistic skin, bed.',
    icon: 'Heart',
    blockIds: ['res_9', 'lig_6', 'sce_2', 'out_12', 'exp_12', 'rea_2'],
    isNsfw: true
  }
];

export const ALL_BLOCKS = [...INFLUENCER_BLOCKS, ...GENERAL_BLOCKS];